// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.auth.credential-state@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:cdfdb6d2fe8c289ec35d9bbe4e4ac9b213da6478d29dab4eeb3a0e1b2a75d25e";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const CREDENTIAL_STATE_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const CREDENTIAL_STATE_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const CREDENTIAL_STATE_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const CREDENTIAL_STATE_CONTRACT: CapabilityReference<CredentialStateClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_credential_state { () => { "{\"capability_id\":\"lenso.auth.credential-state@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"inspect\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_credential_state_client {
    () => { "{\"capability_id\":\"lenso.auth.credential-state@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.credential-state@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_credential_state_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.credential-state@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_credential_state_client {
    () => { "{\"capability_id\":\"lenso.auth.credential-state@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.credential-state@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const INSPECT_OPERATION: &str = "inspect";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InspectRequest {
    #[serde(rename = "credential_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential_id: String,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InspectResponse {
    #[serde(rename = "active")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub active: bool,
    #[serde(rename = "actor_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub actor_kind: String,
    #[serde(rename = "assurance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub assurance: String,
    #[serde(rename = "audience")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub audience: Vec<String>,
    #[serde(rename = "claims")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub claims: std::collections::BTreeMap<String, serde_json::Value>,
    #[serde(rename = "credential_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential_id: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

impl fmt::Debug for InspectResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("InspectResponse")
            .field("active", &self.active)
            .field("actor_kind", &self.actor_kind)
            .field("assurance", &self.assurance)
            .field("audience", &self.audience)
            .field("claims", &"<redacted>")
            .field("credential_id", &self.credential_id)
            .field("expires_at", &self.expires_at)
            .field("session_id", &self.session_id)
            .field("subject", &self.subject)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum InspectError {
    InvalidReference,
    NotFound,
    PermissionDenied,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct CredentialState;
impl RequestCapability for CredentialState {
    type Request = InspectRequest;
    type Response = InspectResponse;
    type DomainError = InspectError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != INSPECT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<CredentialStateRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).inspect(context, request)
    }
}

impl serde::Serialize for InspectError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidReference => serializer.serialize_str("invalid_reference"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for InspectError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_reference" => Ok(Self::InvalidReference),
                "not_found" => Ok(Self::NotFound),
                "permission_denied" => Ok(Self::PermissionDenied),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_inspect_request(value: &InspectRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_inspect_request(wire: &str) -> Result<InspectRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_inspect_response(value: &InspectResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_inspect_response(wire: &str) -> Result<InspectResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_inspect_error(value: &InspectError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_inspect_error(wire: &str) -> Result<InspectError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoCredentialStateInspectResult {
    fn __lenso_into_result(self) -> Result<Result<InspectResponse, InspectError>, RuntimeFailure>;
}
impl __LensoIntoCredentialStateInspectResult for Result<InspectResponse, InspectError> {
    fn __lenso_into_result(self) -> Result<Result<InspectResponse, InspectError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoCredentialStateInspectResult for Result<Result<InspectResponse, InspectError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<InspectResponse, InspectError>, RuntimeFailure> { self }
}
impl __LensoIntoCredentialStateInspectResult for Result<InspectResponse, lenso_plugin_authoring::PluginError<InspectError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<InspectResponse, InspectError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoCredentialStateInspectResult for Result<InspectResponse, CredentialStateInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<InspectResponse, InspectError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(CredentialStateInvocationError::Domain(error)) => Ok(Err(error)),
            Err(CredentialStateInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait CredentialStateProvider: fmt::Debug + 'static {
    fn inspect(&self, context: InvocationContext, request: InspectRequest) -> NativeRequestFuture<CredentialState>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_credential_state {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportCredentialState;
        impl $crate::CredentialStateProvider for $plugin {
        fn inspect(&self, context: __LensoNativeSupportCredentialState::InvocationContext, request: $crate::InspectRequest) -> __LensoNativeSupportCredentialState::NativeRequestFuture<$crate::CredentialState> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::inspect(&plugin, context, request).await;
                $crate::__LensoIntoCredentialStateInspectResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_credential_state {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportCredentialState;
        impl $crate::CredentialStateProvider for $object {
        fn inspect(&self, context: __LensoNativeSupportCredentialState::InvocationContext, request: $crate::InspectRequest) -> __LensoNativeSupportCredentialState::NativeRequestFuture<$crate::CredentialState> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::inspect(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoCredentialStateInspectResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_credential_state {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportCredentialState;
        impl $crate::CredentialStateProvider for $object {
        fn inspect(&self, context: __LensoNativeSupportCredentialState::InvocationContext, request: $crate::InspectRequest) -> __LensoNativeSupportCredentialState::NativeRequestFuture<$crate::CredentialState> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::CredentialStateProvider>::inspect(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct CredentialStateRequestEndpoint { provider: Rc<dyn CredentialStateProvider> }

#[derive(Debug)]
pub struct CredentialStateEndpoint<P: CredentialStateProvider> { provider: Rc<P>, request_endpoint: CredentialStateRequestEndpoint }
impl<P: CredentialStateProvider> CredentialStateEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn CredentialStateProvider> = provider.clone();
        Self { provider, request_endpoint: CredentialStateRequestEndpoint { provider: request_provider } }
    }
}

impl<P: CredentialStateProvider> NativeRequestEndpoint for CredentialStateEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        INSPECT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            INSPECT_OPERATION => {
                let Ok(request) = request.downcast::<InspectRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).inspect(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_credential_state {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::CredentialStateEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_credential_state {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_credential_state!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct CredentialStateClient {
    inspect: NativeRequestHandle<CredentialState>,
}
impl CredentialStateClient {
    pub fn new(handle: NativeRequestHandle<CredentialState>) -> Self {
        Self { inspect: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn inspect(&self, request: InspectRequest) -> Result<InspectResponse, CredentialStateInvocationError> {
        self.inspect.invoke(INSPECT_OPERATION, request).await
            .map_err(CredentialStateInvocationError::Runtime)?
            .map_err(CredentialStateInvocationError::Domain)
    }

    pub async fn inspect_with_context(&self, context: InvocationContext, request: InspectRequest) -> Result<InspectResponse, CredentialStateInvocationError> {
        self.inspect.invoke_with_context(INSPECT_OPERATION, context, request).await
            .map_err(CredentialStateInvocationError::Runtime)?
            .map_err(CredentialStateInvocationError::Domain)
    }
}

impl CapabilityClient for CredentialStateClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            inspect: dependencies.one::<CredentialState>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for CredentialStateClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    inspect: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<CredentialState>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum CredentialStateInvocationError {
    Domain(InspectError),
    Runtime(RuntimeFailure),
}
