// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.auth.delegation@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:a4f285eac16907595b70ef3cdd668e3482c6583d0307703c0af08838f05fe6c0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const DELEGATION_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const DELEGATION_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const DELEGATION_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const DELEGATION_CONTRACT: CapabilityReference<DelegationClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_delegation { () => { "{\"capability_id\":\"lenso.auth.delegation@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"grant\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_delegation_client {
    () => { "{\"capability_id\":\"lenso.auth.delegation@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.delegation@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_delegation_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.delegation@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_delegation_client {
    () => { "{\"capability_id\":\"lenso.auth.delegation@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.delegation@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const GRANT_OPERATION: &str = "grant";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GrantRequest {
    #[serde(rename = "audience")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub audience: Vec<String>,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "parent_credential")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub parent_credential: String,
}

impl fmt::Debug for GrantRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("GrantRequest")
            .field("audience", &self.audience)
            .field("expires_at", &self.expires_at)
            .field("parent_credential", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GrantResponse {
    #[serde(rename = "audience")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub audience: Vec<String>,
    #[serde(rename = "credential")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

impl fmt::Debug for GrantResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("GrantResponse")
            .field("audience", &self.audience)
            .field("credential", &"<redacted>")
            .field("expires_at", &self.expires_at)
            .field("session_id", &self.session_id)
            .field("subject", &self.subject)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum GrantError {
    Expired,
    InvalidCredential,
    InvalidScope,
    NestedDelegation,
    PermissionDenied,
    Revoked,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct Delegation;
impl RequestCapability for Delegation {
    type Request = GrantRequest;
    type Response = GrantResponse;
    type DomainError = GrantError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GRANT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<DelegationRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).grant(context, request)
    }
}

impl serde::Serialize for GrantError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Expired => serializer.serialize_str("expired"),
            Self::InvalidCredential => serializer.serialize_str("invalid_credential"),
            Self::InvalidScope => serializer.serialize_str("invalid_scope"),
            Self::NestedDelegation => serializer.serialize_str("nested_delegation"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::Revoked => serializer.serialize_str("revoked"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GrantError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "expired" => Ok(Self::Expired),
                "invalid_credential" => Ok(Self::InvalidCredential),
                "invalid_scope" => Ok(Self::InvalidScope),
                "nested_delegation" => Ok(Self::NestedDelegation),
                "permission_denied" => Ok(Self::PermissionDenied),
                "revoked" => Ok(Self::Revoked),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_grant_request(value: &GrantRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_grant_request(wire: &str) -> Result<GrantRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_grant_response(value: &GrantResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_grant_response(wire: &str) -> Result<GrantResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_grant_error(value: &GrantError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_grant_error(wire: &str) -> Result<GrantError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoDelegationGrantResult {
    fn __lenso_into_result(self) -> Result<Result<GrantResponse, GrantError>, RuntimeFailure>;
}
impl __LensoIntoDelegationGrantResult for Result<GrantResponse, GrantError> {
    fn __lenso_into_result(self) -> Result<Result<GrantResponse, GrantError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoDelegationGrantResult for Result<Result<GrantResponse, GrantError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GrantResponse, GrantError>, RuntimeFailure> { self }
}
impl __LensoIntoDelegationGrantResult for Result<GrantResponse, lenso_plugin_authoring::PluginError<GrantError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GrantResponse, GrantError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoDelegationGrantResult for Result<GrantResponse, DelegationInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GrantResponse, GrantError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(DelegationInvocationError::Domain(error)) => Ok(Err(error)),
            Err(DelegationInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait DelegationProvider: fmt::Debug + 'static {
    fn grant(&self, context: InvocationContext, request: GrantRequest) -> NativeRequestFuture<Delegation>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_delegation {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportDelegation;
        impl $crate::DelegationProvider for $plugin {
        fn grant(&self, context: __LensoNativeSupportDelegation::InvocationContext, request: $crate::GrantRequest) -> __LensoNativeSupportDelegation::NativeRequestFuture<$crate::Delegation> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::grant(&plugin, context, request).await;
                $crate::__LensoIntoDelegationGrantResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_delegation {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportDelegation;
        impl $crate::DelegationProvider for $object {
        fn grant(&self, context: __LensoNativeSupportDelegation::InvocationContext, request: $crate::GrantRequest) -> __LensoNativeSupportDelegation::NativeRequestFuture<$crate::Delegation> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::grant(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoDelegationGrantResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_delegation {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportDelegation;
        impl $crate::DelegationProvider for $object {
        fn grant(&self, context: __LensoNativeSupportDelegation::InvocationContext, request: $crate::GrantRequest) -> __LensoNativeSupportDelegation::NativeRequestFuture<$crate::Delegation> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::DelegationProvider>::grant(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct DelegationRequestEndpoint { provider: Rc<dyn DelegationProvider> }

#[derive(Debug)]
pub struct DelegationEndpoint<P: DelegationProvider> { provider: Rc<P>, request_endpoint: DelegationRequestEndpoint }
impl<P: DelegationProvider> DelegationEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn DelegationProvider> = provider.clone();
        Self { provider, request_endpoint: DelegationRequestEndpoint { provider: request_provider } }
    }
}

impl<P: DelegationProvider> NativeRequestEndpoint for DelegationEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        GRANT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            GRANT_OPERATION => {
                let Ok(request) = request.downcast::<GrantRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).grant(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_delegation {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::DelegationEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_delegation {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_delegation!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct DelegationClient {
    grant: NativeRequestHandle<Delegation>,
}
impl DelegationClient {
    pub fn new(handle: NativeRequestHandle<Delegation>) -> Self {
        Self { grant: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn grant(&self, request: GrantRequest) -> Result<GrantResponse, DelegationInvocationError> {
        self.grant.invoke(GRANT_OPERATION, request).await
            .map_err(DelegationInvocationError::Runtime)?
            .map_err(DelegationInvocationError::Domain)
    }

    pub async fn grant_with_context(&self, context: InvocationContext, request: GrantRequest) -> Result<GrantResponse, DelegationInvocationError> {
        self.grant.invoke_with_context(GRANT_OPERATION, context, request).await
            .map_err(DelegationInvocationError::Runtime)?
            .map_err(DelegationInvocationError::Domain)
    }
}

impl CapabilityClient for DelegationClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            grant: dependencies.one::<Delegation>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for DelegationClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    grant: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<Delegation>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum DelegationInvocationError {
    Domain(GrantError),
    Runtime(RuntimeFailure),
}
