// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.auth.profile-cache@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:1ab3a7aad7bc8c91ad8fa1088249f211f5778c94aaa7d6da107c959b710a1161";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const PROFILE_CACHE_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const PROFILE_CACHE_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const PROFILE_CACHE_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const PROFILE_CACHE_CONTRACT: CapabilityReference<ProfileCacheClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_profile_cache { () => { "{\"capability_id\":\"lenso.auth.profile-cache@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"get\",\"put\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_profile_cache_client {
    () => { "{\"capability_id\":\"lenso.auth.profile-cache@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.profile-cache@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_profile_cache_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.profile-cache@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_profile_cache_client {
    () => { "{\"capability_id\":\"lenso.auth.profile-cache@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.profile-cache@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const GET_OPERATION: &str = "get";
pub const PUT_OPERATION: &str = "put";

pub use lenso_contract_runtime::{OptionalValue, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetRequest {
    #[serde(rename = "namespace")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub namespace: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetResponse {
    #[serde(rename = "avatar_url")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub avatar_url: OptionalValue<String>,
    #[serde(rename = "display_name")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub display_name: OptionalValue<String>,
    #[serde(rename = "found")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub found: bool,
    #[serde(rename = "revision")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub revision: OptionalValue<i64>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum GetError {
    InvalidRequest,
    PermissionDenied,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PutRequest {
    #[serde(rename = "avatar_url")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub avatar_url: OptionalValue<String>,
    #[serde(rename = "display_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub display_name: String,
    #[serde(rename = "namespace")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub namespace: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: i64,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PutResponse {
    #[serde(rename = "stored")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub stored: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum PutError {
    InvalidRequest,
    PermissionDenied,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct ProfileCacheGet;
impl RequestCapability for ProfileCacheGet {
    type Request = GetRequest;
    type Response = GetResponse;
    type DomainError = GetError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GET_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ProfileCacheRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).get(context, request)
    }
}

#[derive(Debug)]
pub struct ProfileCachePut;
impl RequestCapability for ProfileCachePut {
    type Request = PutRequest;
    type Response = PutResponse;
    type DomainError = PutError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != PUT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ProfileCacheRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).put(context, request)
    }
}

impl serde::Serialize for GetError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GetError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_request" => Ok(Self::InvalidRequest),
                "permission_denied" => Ok(Self::PermissionDenied),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for PutError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for PutError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_request" => Ok(Self::InvalidRequest),
                "permission_denied" => Ok(Self::PermissionDenied),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_get_request(value: &GetRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_request(wire: &str) -> Result<GetRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_response(value: &GetResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_response(wire: &str) -> Result<GetResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_error(value: &GetError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_error(wire: &str) -> Result<GetError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_put_request(value: &PutRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_put_request(wire: &str) -> Result<PutRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_put_response(value: &PutResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_put_response(wire: &str) -> Result<PutResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_put_error(value: &PutError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_put_error(wire: &str) -> Result<PutError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoProfileCacheGetResult {
    fn __lenso_into_result(self) -> Result<Result<GetResponse, GetError>, RuntimeFailure>;
}
impl __LensoIntoProfileCacheGetResult for Result<GetResponse, GetError> {
    fn __lenso_into_result(self) -> Result<Result<GetResponse, GetError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoProfileCacheGetResult for Result<Result<GetResponse, GetError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GetResponse, GetError>, RuntimeFailure> { self }
}
impl __LensoIntoProfileCacheGetResult for Result<GetResponse, lenso_plugin_authoring::PluginError<GetError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GetResponse, GetError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoProfileCacheGetResult for Result<GetResponse, ProfileCacheGetInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GetResponse, GetError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ProfileCacheGetInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ProfileCacheGetInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoProfileCachePutResult {
    fn __lenso_into_result(self) -> Result<Result<PutResponse, PutError>, RuntimeFailure>;
}
impl __LensoIntoProfileCachePutResult for Result<PutResponse, PutError> {
    fn __lenso_into_result(self) -> Result<Result<PutResponse, PutError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoProfileCachePutResult for Result<Result<PutResponse, PutError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<PutResponse, PutError>, RuntimeFailure> { self }
}
impl __LensoIntoProfileCachePutResult for Result<PutResponse, lenso_plugin_authoring::PluginError<PutError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<PutResponse, PutError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoProfileCachePutResult for Result<PutResponse, ProfileCachePutInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<PutResponse, PutError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ProfileCachePutInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ProfileCachePutInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait ProfileCacheProvider: fmt::Debug + 'static {
    fn get(&self, context: InvocationContext, request: GetRequest) -> NativeRequestFuture<ProfileCacheGet>;
    fn put(&self, context: InvocationContext, request: PutRequest) -> NativeRequestFuture<ProfileCachePut>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_profile_cache {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportProfileCache;
        impl $crate::ProfileCacheProvider for $plugin {
        fn get(&self, context: __LensoNativeSupportProfileCache::InvocationContext, request: $crate::GetRequest) -> __LensoNativeSupportProfileCache::NativeRequestFuture<$crate::ProfileCacheGet> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::get(&plugin, context, request).await;
                $crate::__LensoIntoProfileCacheGetResult::__lenso_into_result(result)
            })
        }
        fn put(&self, context: __LensoNativeSupportProfileCache::InvocationContext, request: $crate::PutRequest) -> __LensoNativeSupportProfileCache::NativeRequestFuture<$crate::ProfileCachePut> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::put(&plugin, context, request).await;
                $crate::__LensoIntoProfileCachePutResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_profile_cache {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportProfileCache;
        impl $crate::ProfileCacheProvider for $object {
        fn get(&self, context: __LensoNativeSupportProfileCache::InvocationContext, request: $crate::GetRequest) -> __LensoNativeSupportProfileCache::NativeRequestFuture<$crate::ProfileCacheGet> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::get(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoProfileCacheGetResult::__lenso_into_result(result)
            })
        }
        fn put(&self, context: __LensoNativeSupportProfileCache::InvocationContext, request: $crate::PutRequest) -> __LensoNativeSupportProfileCache::NativeRequestFuture<$crate::ProfileCachePut> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::put(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoProfileCachePutResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_profile_cache {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportProfileCache;
        impl $crate::ProfileCacheProvider for $object {
        fn get(&self, context: __LensoNativeSupportProfileCache::InvocationContext, request: $crate::GetRequest) -> __LensoNativeSupportProfileCache::NativeRequestFuture<$crate::ProfileCacheGet> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::ProfileCacheProvider>::get(plugin.as_ref(), context, request).await
            })
        }
        fn put(&self, context: __LensoNativeSupportProfileCache::InvocationContext, request: $crate::PutRequest) -> __LensoNativeSupportProfileCache::NativeRequestFuture<$crate::ProfileCachePut> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::ProfileCacheProvider>::put(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct ProfileCacheRequestEndpoint { provider: Rc<dyn ProfileCacheProvider> }

#[derive(Debug)]
pub struct ProfileCacheEndpoint<P: ProfileCacheProvider> { provider: Rc<P>, request_endpoint: ProfileCacheRequestEndpoint }
impl<P: ProfileCacheProvider> ProfileCacheEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn ProfileCacheProvider> = provider.clone();
        Self { provider, request_endpoint: ProfileCacheRequestEndpoint { provider: request_provider } }
    }
}

impl<P: ProfileCacheProvider> NativeRequestEndpoint for ProfileCacheEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        GET_OPERATION,
        PUT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            GET_OPERATION => {
                let Ok(request) = request.downcast::<GetRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).get(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            PUT_OPERATION => {
                let Ok(request) = request.downcast::<PutRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).put(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_profile_cache {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::ProfileCacheEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_profile_cache {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_profile_cache!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct ProfileCacheClient {
    get: NativeRequestHandle<ProfileCacheGet>,
    put: NativeRequestHandle<ProfileCachePut>,
}
impl ProfileCacheClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn get(&self, request: GetRequest) -> Result<GetResponse, ProfileCacheGetInvocationError> {
        self.get.invoke(GET_OPERATION, request).await
            .map_err(ProfileCacheGetInvocationError::Runtime)?
            .map_err(ProfileCacheGetInvocationError::Domain)
    }

    pub async fn get_with_context(&self, context: InvocationContext, request: GetRequest) -> Result<GetResponse, ProfileCacheGetInvocationError> {
        self.get.invoke_with_context(GET_OPERATION, context, request).await
            .map_err(ProfileCacheGetInvocationError::Runtime)?
            .map_err(ProfileCacheGetInvocationError::Domain)
    }

    pub async fn put(&self, request: PutRequest) -> Result<PutResponse, ProfileCachePutInvocationError> {
        self.put.invoke(PUT_OPERATION, request).await
            .map_err(ProfileCachePutInvocationError::Runtime)?
            .map_err(ProfileCachePutInvocationError::Domain)
    }

    pub async fn put_with_context(&self, context: InvocationContext, request: PutRequest) -> Result<PutResponse, ProfileCachePutInvocationError> {
        self.put.invoke_with_context(PUT_OPERATION, context, request).await
            .map_err(ProfileCachePutInvocationError::Runtime)?
            .map_err(ProfileCachePutInvocationError::Domain)
    }
}

impl CapabilityClient for ProfileCacheClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            get: dependencies.one::<ProfileCacheGet>()?,
            put: dependencies.one::<ProfileCachePut>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for ProfileCacheClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    get: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ProfileCacheGet>()?,
                    put: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ProfileCachePut>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ProfileCacheGetInvocationError {
    Domain(GetError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ProfileCachePutInvocationError {
    Domain(PutError),
    Runtime(RuntimeFailure),
}
