// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.auth.password@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:2a2df78ace73073ebfc1b1a8f079c337ea3d2e47c1afba23c31f2b5279dcba7c";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const PASSWORD_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const PASSWORD_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const PASSWORD_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const PASSWORD_CONTRACT: CapabilityReference<PasswordClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_password { () => { "{\"capability_id\":\"lenso.auth.password@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"login\",\"register\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_password_client {
    () => { "{\"capability_id\":\"lenso.auth.password@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.password@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_password_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.password@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_password_client {
    () => { "{\"capability_id\":\"lenso.auth.password@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.password@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const LOGIN_OPERATION: &str = "login";
pub const REGISTER_OPERATION: &str = "register";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LoginRequest {
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "password")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub password: String,
}

impl fmt::Debug for LoginRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("LoginRequest")
            .field("identifier", &self.identifier)
            .field("password", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LoginResponse {
    #[serde(rename = "credential")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

impl fmt::Debug for LoginResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("LoginResponse")
            .field("credential", &"<redacted>")
            .field("expires_at", &self.expires_at)
            .field("session_id", &self.session_id)
            .field("subject", &self.subject)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum LoginError {
    Disabled,
    InvalidCredentials,
    InvalidIdentifier,
    RateLimited,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RegisterRequest {
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "password")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub password: String,
}

impl fmt::Debug for RegisterRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("RegisterRequest")
            .field("identifier", &self.identifier)
            .field("password", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RegisterResponse {
    #[serde(rename = "credential")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

impl fmt::Debug for RegisterResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("RegisterResponse")
            .field("credential", &"<redacted>")
            .field("expires_at", &self.expires_at)
            .field("session_id", &self.session_id)
            .field("subject", &self.subject)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum RegisterError {
    Disabled,
    IdentifierTaken,
    InvalidIdentifier,
    WeakPassword,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct PasswordLogin;
impl RequestCapability for PasswordLogin {
    type Request = LoginRequest;
    type Response = LoginResponse;
    type DomainError = LoginError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LOGIN_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PasswordRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).login(context, request)
    }
}

#[derive(Debug)]
pub struct PasswordRegister;
impl RequestCapability for PasswordRegister {
    type Request = RegisterRequest;
    type Response = RegisterResponse;
    type DomainError = RegisterError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != REGISTER_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PasswordRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).register(context, request)
    }
}

impl serde::Serialize for LoginError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Disabled => serializer.serialize_str("disabled"),
            Self::InvalidCredentials => serializer.serialize_str("invalid_credentials"),
            Self::InvalidIdentifier => serializer.serialize_str("invalid_identifier"),
            Self::RateLimited => serializer.serialize_str("rate_limited"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for LoginError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "disabled" => Ok(Self::Disabled),
                "invalid_credentials" => Ok(Self::InvalidCredentials),
                "invalid_identifier" => Ok(Self::InvalidIdentifier),
                "rate_limited" => Ok(Self::RateLimited),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RegisterError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Disabled => serializer.serialize_str("disabled"),
            Self::IdentifierTaken => serializer.serialize_str("identifier_taken"),
            Self::InvalidIdentifier => serializer.serialize_str("invalid_identifier"),
            Self::WeakPassword => serializer.serialize_str("weak_password"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RegisterError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "disabled" => Ok(Self::Disabled),
                "identifier_taken" => Ok(Self::IdentifierTaken),
                "invalid_identifier" => Ok(Self::InvalidIdentifier),
                "weak_password" => Ok(Self::WeakPassword),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_login_request(value: &LoginRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_login_request(wire: &str) -> Result<LoginRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_login_response(value: &LoginResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_login_response(wire: &str) -> Result<LoginResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_login_error(value: &LoginError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_login_error(wire: &str) -> Result<LoginError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_register_request(value: &RegisterRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_register_request(wire: &str) -> Result<RegisterRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_register_response(value: &RegisterResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_register_response(wire: &str) -> Result<RegisterResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_register_error(value: &RegisterError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_register_error(wire: &str) -> Result<RegisterError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoPasswordLoginResult {
    fn __lenso_into_result(self) -> Result<Result<LoginResponse, LoginError>, RuntimeFailure>;
}
impl __LensoIntoPasswordLoginResult for Result<LoginResponse, LoginError> {
    fn __lenso_into_result(self) -> Result<Result<LoginResponse, LoginError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoPasswordLoginResult for Result<Result<LoginResponse, LoginError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<LoginResponse, LoginError>, RuntimeFailure> { self }
}
impl __LensoIntoPasswordLoginResult for Result<LoginResponse, lenso_plugin_authoring::PluginError<LoginError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<LoginResponse, LoginError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoPasswordLoginResult for Result<LoginResponse, PasswordLoginInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<LoginResponse, LoginError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(PasswordLoginInvocationError::Domain(error)) => Ok(Err(error)),
            Err(PasswordLoginInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoPasswordRegisterResult {
    fn __lenso_into_result(self) -> Result<Result<RegisterResponse, RegisterError>, RuntimeFailure>;
}
impl __LensoIntoPasswordRegisterResult for Result<RegisterResponse, RegisterError> {
    fn __lenso_into_result(self) -> Result<Result<RegisterResponse, RegisterError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoPasswordRegisterResult for Result<Result<RegisterResponse, RegisterError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<RegisterResponse, RegisterError>, RuntimeFailure> { self }
}
impl __LensoIntoPasswordRegisterResult for Result<RegisterResponse, lenso_plugin_authoring::PluginError<RegisterError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<RegisterResponse, RegisterError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoPasswordRegisterResult for Result<RegisterResponse, PasswordRegisterInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<RegisterResponse, RegisterError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(PasswordRegisterInvocationError::Domain(error)) => Ok(Err(error)),
            Err(PasswordRegisterInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait PasswordProvider: fmt::Debug + 'static {
    fn login(&self, context: InvocationContext, request: LoginRequest) -> NativeRequestFuture<PasswordLogin>;
    fn register(&self, context: InvocationContext, request: RegisterRequest) -> NativeRequestFuture<PasswordRegister>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_password {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportPassword;
        impl $crate::PasswordProvider for $plugin {
        fn login(&self, context: __LensoNativeSupportPassword::InvocationContext, request: $crate::LoginRequest) -> __LensoNativeSupportPassword::NativeRequestFuture<$crate::PasswordLogin> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::login(&plugin, context, request).await;
                $crate::__LensoIntoPasswordLoginResult::__lenso_into_result(result)
            })
        }
        fn register(&self, context: __LensoNativeSupportPassword::InvocationContext, request: $crate::RegisterRequest) -> __LensoNativeSupportPassword::NativeRequestFuture<$crate::PasswordRegister> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::register(&plugin, context, request).await;
                $crate::__LensoIntoPasswordRegisterResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_password {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportPassword;
        impl $crate::PasswordProvider for $object {
        fn login(&self, context: __LensoNativeSupportPassword::InvocationContext, request: $crate::LoginRequest) -> __LensoNativeSupportPassword::NativeRequestFuture<$crate::PasswordLogin> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::login(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoPasswordLoginResult::__lenso_into_result(result)
            })
        }
        fn register(&self, context: __LensoNativeSupportPassword::InvocationContext, request: $crate::RegisterRequest) -> __LensoNativeSupportPassword::NativeRequestFuture<$crate::PasswordRegister> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::register(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoPasswordRegisterResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_password {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportPassword;
        impl $crate::PasswordProvider for $object {
        fn login(&self, context: __LensoNativeSupportPassword::InvocationContext, request: $crate::LoginRequest) -> __LensoNativeSupportPassword::NativeRequestFuture<$crate::PasswordLogin> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::PasswordProvider>::login(plugin.as_ref(), context, request).await
            })
        }
        fn register(&self, context: __LensoNativeSupportPassword::InvocationContext, request: $crate::RegisterRequest) -> __LensoNativeSupportPassword::NativeRequestFuture<$crate::PasswordRegister> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::PasswordProvider>::register(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct PasswordRequestEndpoint { provider: Rc<dyn PasswordProvider> }

#[derive(Debug)]
pub struct PasswordEndpoint<P: PasswordProvider> { provider: Rc<P>, request_endpoint: PasswordRequestEndpoint }
impl<P: PasswordProvider> PasswordEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn PasswordProvider> = provider.clone();
        Self { provider, request_endpoint: PasswordRequestEndpoint { provider: request_provider } }
    }
}

impl<P: PasswordProvider> NativeRequestEndpoint for PasswordEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        LOGIN_OPERATION,
        REGISTER_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            LOGIN_OPERATION => {
                let Ok(request) = request.downcast::<LoginRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).login(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            REGISTER_OPERATION => {
                let Ok(request) = request.downcast::<RegisterRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).register(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_password {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::PasswordEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_password {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_password!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct PasswordClient {
    login: NativeRequestHandle<PasswordLogin>,
    register: NativeRequestHandle<PasswordRegister>,
}
impl PasswordClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn login(&self, request: LoginRequest) -> Result<LoginResponse, PasswordLoginInvocationError> {
        self.login.invoke(LOGIN_OPERATION, request).await
            .map_err(PasswordLoginInvocationError::Runtime)?
            .map_err(PasswordLoginInvocationError::Domain)
    }

    pub async fn login_with_context(&self, context: InvocationContext, request: LoginRequest) -> Result<LoginResponse, PasswordLoginInvocationError> {
        self.login.invoke_with_context(LOGIN_OPERATION, context, request).await
            .map_err(PasswordLoginInvocationError::Runtime)?
            .map_err(PasswordLoginInvocationError::Domain)
    }

    pub async fn register(&self, request: RegisterRequest) -> Result<RegisterResponse, PasswordRegisterInvocationError> {
        self.register.invoke(REGISTER_OPERATION, request).await
            .map_err(PasswordRegisterInvocationError::Runtime)?
            .map_err(PasswordRegisterInvocationError::Domain)
    }

    pub async fn register_with_context(&self, context: InvocationContext, request: RegisterRequest) -> Result<RegisterResponse, PasswordRegisterInvocationError> {
        self.register.invoke_with_context(REGISTER_OPERATION, context, request).await
            .map_err(PasswordRegisterInvocationError::Runtime)?
            .map_err(PasswordRegisterInvocationError::Domain)
    }
}

impl CapabilityClient for PasswordClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            login: dependencies.one::<PasswordLogin>()?,
            register: dependencies.one::<PasswordRegister>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for PasswordClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    login: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<PasswordLogin>()?,
                    register: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<PasswordRegister>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum PasswordLoginInvocationError {
    Domain(LoginError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum PasswordRegisterInvocationError {
    Domain(RegisterError),
    Runtime(RuntimeFailure),
}
