// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.auth.oauth-flow@1";
pub const DESCRIPTOR_VERSION: &str = "1.1.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:a55935c93c9606330562a9d375997a9c3ee5258957cb7c6f9c44e7b852d2f5ba";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const OAUTH_FLOW_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const OAUTH_FLOW_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const OAUTH_FLOW_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const OAUTH_FLOW_CONTRACT: CapabilityReference<OauthFlowClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_oauth_flow { () => { "{\"capability_id\":\"lenso.auth.oauth-flow@1\",\"descriptor_version\":\"1.1.0\",\"operations\":[\"consume\",\"create\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_oauth_flow_client {
    () => { "{\"capability_id\":\"lenso.auth.oauth-flow@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.oauth-flow@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_oauth_flow_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.oauth-flow@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_oauth_flow_client {
    () => { "{\"capability_id\":\"lenso.auth.oauth-flow@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.oauth-flow@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"many\"}") };
}

pub const CONSUME_OPERATION: &str = "consume";
pub const CREATE_OPERATION: &str = "create";

pub use lenso_contract_runtime::{OptionalValue, Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ConsumeRequest {
    #[serde(rename = "provider")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provider: String,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: String,
}

impl fmt::Debug for ConsumeRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ConsumeRequest")
            .field("provider", &self.provider)
            .field("state", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ConsumeResponse {
    #[serde(rename = "code_verifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub code_verifier: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "nonce")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub nonce: OptionalValue<String>,
    #[serde(rename = "return_to")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub return_to: String,
}

impl fmt::Debug for ConsumeResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ConsumeResponse")
            .field("code_verifier", &"<redacted>")
            .field("expires_at", &self.expires_at)
            .field("nonce", &"<redacted>")
            .field("return_to", &self.return_to)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ConsumeError {
    AlreadyConsumed,
    Expired,
    InvalidState,
    ProviderMismatch,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateRequest {
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "provider")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provider: String,
    #[serde(rename = "return_to")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub return_to: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateResponse {
    #[serde(rename = "code_challenge")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub code_challenge: String,
    #[serde(rename = "code_verifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub code_verifier: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "nonce")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub nonce: OptionalValue<String>,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: String,
}

impl fmt::Debug for CreateResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("CreateResponse")
            .field("code_challenge", &self.code_challenge)
            .field("code_verifier", &"<redacted>")
            .field("expires_at", &self.expires_at)
            .field("nonce", &"<redacted>")
            .field("state", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum CreateError {
    InvalidExpiry,
    InvalidProvider,
    InvalidReturnTo,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct OauthFlowConsume;
impl RequestCapability for OauthFlowConsume {
    type Request = ConsumeRequest;
    type Response = ConsumeResponse;
    type DomainError = ConsumeError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CONSUME_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OauthFlowRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).consume(context, request)
    }
}

#[derive(Debug)]
pub struct OauthFlowCreate;
impl RequestCapability for OauthFlowCreate {
    type Request = CreateRequest;
    type Response = CreateResponse;
    type DomainError = CreateError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CREATE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OauthFlowRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).create(context, request)
    }
}

impl serde::Serialize for ConsumeError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AlreadyConsumed => serializer.serialize_str("already_consumed"),
            Self::Expired => serializer.serialize_str("expired"),
            Self::InvalidState => serializer.serialize_str("invalid_state"),
            Self::ProviderMismatch => serializer.serialize_str("provider_mismatch"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ConsumeError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "already_consumed" => Ok(Self::AlreadyConsumed),
                "expired" => Ok(Self::Expired),
                "invalid_state" => Ok(Self::InvalidState),
                "provider_mismatch" => Ok(Self::ProviderMismatch),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for CreateError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidExpiry => serializer.serialize_str("invalid_expiry"),
            Self::InvalidProvider => serializer.serialize_str("invalid_provider"),
            Self::InvalidReturnTo => serializer.serialize_str("invalid_return_to"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CreateError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_expiry" => Ok(Self::InvalidExpiry),
                "invalid_provider" => Ok(Self::InvalidProvider),
                "invalid_return_to" => Ok(Self::InvalidReturnTo),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_consume_request(value: &ConsumeRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_consume_request(wire: &str) -> Result<ConsumeRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_consume_response(value: &ConsumeResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_consume_response(wire: &str) -> Result<ConsumeResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_consume_error(value: &ConsumeError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_consume_error(wire: &str) -> Result<ConsumeError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_create_request(value: &CreateRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_request(wire: &str) -> Result<CreateRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_response(value: &CreateResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_response(wire: &str) -> Result<CreateResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_error(value: &CreateError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_error(wire: &str) -> Result<CreateError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoOauthFlowConsumeResult {
    fn __lenso_into_result(self) -> Result<Result<ConsumeResponse, ConsumeError>, RuntimeFailure>;
}
impl __LensoIntoOauthFlowConsumeResult for Result<ConsumeResponse, ConsumeError> {
    fn __lenso_into_result(self) -> Result<Result<ConsumeResponse, ConsumeError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOauthFlowConsumeResult for Result<Result<ConsumeResponse, ConsumeError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ConsumeResponse, ConsumeError>, RuntimeFailure> { self }
}
impl __LensoIntoOauthFlowConsumeResult for Result<ConsumeResponse, lenso_plugin_authoring::PluginError<ConsumeError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ConsumeResponse, ConsumeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOauthFlowConsumeResult for Result<ConsumeResponse, OauthFlowConsumeInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ConsumeResponse, ConsumeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OauthFlowConsumeInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OauthFlowConsumeInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOauthFlowCreateResult {
    fn __lenso_into_result(self) -> Result<Result<CreateResponse, CreateError>, RuntimeFailure>;
}
impl __LensoIntoOauthFlowCreateResult for Result<CreateResponse, CreateError> {
    fn __lenso_into_result(self) -> Result<Result<CreateResponse, CreateError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOauthFlowCreateResult for Result<Result<CreateResponse, CreateError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CreateResponse, CreateError>, RuntimeFailure> { self }
}
impl __LensoIntoOauthFlowCreateResult for Result<CreateResponse, lenso_plugin_authoring::PluginError<CreateError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CreateResponse, CreateError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOauthFlowCreateResult for Result<CreateResponse, OauthFlowCreateInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CreateResponse, CreateError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OauthFlowCreateInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OauthFlowCreateInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait OauthFlowProvider: fmt::Debug + 'static {
    fn consume(&self, context: InvocationContext, request: ConsumeRequest) -> NativeRequestFuture<OauthFlowConsume>;
    fn create(&self, context: InvocationContext, request: CreateRequest) -> NativeRequestFuture<OauthFlowCreate>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_oauth_flow {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportOauthFlow;
        impl $crate::OauthFlowProvider for $plugin {
        fn consume(&self, context: __LensoNativeSupportOauthFlow::InvocationContext, request: $crate::ConsumeRequest) -> __LensoNativeSupportOauthFlow::NativeRequestFuture<$crate::OauthFlowConsume> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::consume(&plugin, context, request).await;
                $crate::__LensoIntoOauthFlowConsumeResult::__lenso_into_result(result)
            })
        }
        fn create(&self, context: __LensoNativeSupportOauthFlow::InvocationContext, request: $crate::CreateRequest) -> __LensoNativeSupportOauthFlow::NativeRequestFuture<$crate::OauthFlowCreate> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::create(&plugin, context, request).await;
                $crate::__LensoIntoOauthFlowCreateResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_oauth_flow {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportOauthFlow;
        impl $crate::OauthFlowProvider for $object {
        fn consume(&self, context: __LensoNativeSupportOauthFlow::InvocationContext, request: $crate::ConsumeRequest) -> __LensoNativeSupportOauthFlow::NativeRequestFuture<$crate::OauthFlowConsume> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::consume(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoOauthFlowConsumeResult::__lenso_into_result(result)
            })
        }
        fn create(&self, context: __LensoNativeSupportOauthFlow::InvocationContext, request: $crate::CreateRequest) -> __LensoNativeSupportOauthFlow::NativeRequestFuture<$crate::OauthFlowCreate> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::create(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoOauthFlowCreateResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_oauth_flow {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportOauthFlow;
        impl $crate::OauthFlowProvider for $object {
        fn consume(&self, context: __LensoNativeSupportOauthFlow::InvocationContext, request: $crate::ConsumeRequest) -> __LensoNativeSupportOauthFlow::NativeRequestFuture<$crate::OauthFlowConsume> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::OauthFlowProvider>::consume(plugin.as_ref(), context, request).await
            })
        }
        fn create(&self, context: __LensoNativeSupportOauthFlow::InvocationContext, request: $crate::CreateRequest) -> __LensoNativeSupportOauthFlow::NativeRequestFuture<$crate::OauthFlowCreate> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::OauthFlowProvider>::create(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct OauthFlowRequestEndpoint { provider: Rc<dyn OauthFlowProvider> }

#[derive(Debug)]
pub struct OauthFlowEndpoint<P: OauthFlowProvider> { provider: Rc<P>, request_endpoint: OauthFlowRequestEndpoint }
impl<P: OauthFlowProvider> OauthFlowEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn OauthFlowProvider> = provider.clone();
        Self { provider, request_endpoint: OauthFlowRequestEndpoint { provider: request_provider } }
    }
}

impl<P: OauthFlowProvider> NativeRequestEndpoint for OauthFlowEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CONSUME_OPERATION,
        CREATE_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CONSUME_OPERATION => {
                let Ok(request) = request.downcast::<ConsumeRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).consume(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            CREATE_OPERATION => {
                let Ok(request) = request.downcast::<CreateRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).create(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_oauth_flow {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::OauthFlowEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_oauth_flow {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_oauth_flow!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct OauthFlowClient {
    consume: NativeRequestHandle<OauthFlowConsume>,
    create: NativeRequestHandle<OauthFlowCreate>,
}
impl OauthFlowClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn consume(&self, request: ConsumeRequest) -> Result<ConsumeResponse, OauthFlowConsumeInvocationError> {
        self.consume.invoke(CONSUME_OPERATION, request).await
            .map_err(OauthFlowConsumeInvocationError::Runtime)?
            .map_err(OauthFlowConsumeInvocationError::Domain)
    }

    pub async fn consume_with_context(&self, context: InvocationContext, request: ConsumeRequest) -> Result<ConsumeResponse, OauthFlowConsumeInvocationError> {
        self.consume.invoke_with_context(CONSUME_OPERATION, context, request).await
            .map_err(OauthFlowConsumeInvocationError::Runtime)?
            .map_err(OauthFlowConsumeInvocationError::Domain)
    }

    pub async fn create(&self, request: CreateRequest) -> Result<CreateResponse, OauthFlowCreateInvocationError> {
        self.create.invoke(CREATE_OPERATION, request).await
            .map_err(OauthFlowCreateInvocationError::Runtime)?
            .map_err(OauthFlowCreateInvocationError::Domain)
    }

    pub async fn create_with_context(&self, context: InvocationContext, request: CreateRequest) -> Result<CreateResponse, OauthFlowCreateInvocationError> {
        self.create.invoke_with_context(CREATE_OPERATION, context, request).await
            .map_err(OauthFlowCreateInvocationError::Runtime)?
            .map_err(OauthFlowCreateInvocationError::Domain)
    }
}

impl CapabilityClient for OauthFlowClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            consume: dependencies.one::<OauthFlowConsume>()?,
            create: dependencies.one::<OauthFlowCreate>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for OauthFlowClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    consume: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OauthFlowConsume>()?,
                    create: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OauthFlowCreate>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum OauthFlowConsumeInvocationError {
    Domain(ConsumeError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OauthFlowCreateInvocationError {
    Domain(CreateError),
    Runtime(RuntimeFailure),
}
