// Generated by workers/generate-migrations.py. Do not edit.
//! Explicit D1 schema operator and read-only runtime verification.
use crate::workers::D1Binding;
use lenso_migration::Migration;
use lenso_migration_d1::{Error, LegacySchema, Plan, SqlMigration, Statement, Transport};

const MIGRATIONS: &[Migration] = &[Migration::new(
    1,
    "phone",
    include_str!("../migrations/d1/001_phone.sql"),
)];
const SQL: &[SqlMigration] = &[SqlMigration {
    migration: MIGRATIONS[0],
    statement_ends: &[87, 174, 528, 617, 707, 846, 926, 1005, 1085, 1194],
}];
pub fn plan() -> Result<Plan, Error> {
    Plan::new(
        "lenso.auth.phone",
        SQL,
        MIGRATIONS,
        Some(LegacySchema {
            table: "auth_phone_schema",
            fingerprint: "a43943ded1db550678ceed87ba38b8d24925bfe35b56bafdec2ecdd6ca428c3a",
        }),
    )
}

impl Transport for D1Binding {
    fn batch(
        &self,
        statements: Vec<Statement>,
    ) -> std::pin::Pin<
        Box<dyn std::future::Future<Output = Result<Vec<Vec<serde_json::Value>>, Error>> + '_>,
    > {
        Box::pin(async move {
            self.run(
                statements
                    .into_iter()
                    .map(|s| crate::workers::statement(s.sql, s.params))
                    .collect(),
            )
            .await
            .map(|results| results.into_iter().map(|r| r.results).collect())
            .map_err(|()| Error::Transport)
        })
    }
}

/// Runtime Ready gate; never changes storage.
pub async fn verify(binding: &D1Binding) -> Result<(), Error> {
    plan()?.verify(binding).await
}
/// Explicit deployment operation for a fresh dedicated database.
pub async fn setup(binding: &D1Binding) -> Result<(), Error> {
    plan()?.setup(binding).await
}
/// Explicit deployment operation for an existing managed database.
pub async fn upgrade(binding: &D1Binding) -> Result<(), Error> {
    plan()?.upgrade(binding).await
}
/// Explicitly register the known legacy v1, without replaying its SQL.
pub async fn adopt_legacy(binding: &D1Binding) -> Result<(), Error> {
    plan()?.adopt_legacy(binding).await
}
