// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.auth.operator-session@1";
pub const DESCRIPTOR_VERSION: &str = "1.1.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:84c30183fea3c12133a4c2b1ceb8ebc368228740b1157c5e94d8ac338e77f825";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const OPERATOR_SESSION_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const OPERATOR_SESSION_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const OPERATOR_SESSION_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const OPERATOR_SESSION_CONTRACT: CapabilityReference<OperatorSessionClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_operator_session { () => { "{\"capability_id\":\"lenso.auth.operator-session@1\",\"descriptor_version\":\"1.1.0\",\"operations\":[\"bootstrap_binding\",\"exchange_session\",\"read_binding\",\"recover_revocation\",\"resume_binding\",\"revoke_binding\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_operator_session_client {
    () => { "{\"capability_id\":\"lenso.auth.operator-session@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.operator-session@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_operator_session_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.operator-session@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_operator_session_client {
    () => { "{\"capability_id\":\"lenso.auth.operator-session@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.operator-session@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"many\"}") };
}

pub const BOOTSTRAP_BINDING_OPERATION: &str = "bootstrap_binding";
pub const EXCHANGE_SESSION_OPERATION: &str = "exchange_session";
pub const READ_BINDING_OPERATION: &str = "read_binding";
pub const RECOVER_REVOCATION_OPERATION: &str = "recover_revocation";
pub const RESUME_BINDING_OPERATION: &str = "resume_binding";
pub const REVOKE_BINDING_OPERATION: &str = "revoke_binding";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Copy, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct EmptyRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Binding {
    #[serde(rename = "active")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub active: bool,
    #[serde(rename = "audit_event_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub audit_event_id: String,
    #[serde(rename = "binding_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub binding_id: String,
    #[serde(rename = "deployment")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub deployment: String,
    #[serde(rename = "operator_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub operator_subject: String,
    #[serde(rename = "policy_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub policy_revision: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "revocation_audit_event_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revocation_audit_event_id: String,
    #[serde(rename = "revocation_pending")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revocation_pending: bool,
    #[serde(rename = "revoked")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revoked: bool,
    #[serde(rename = "revoked_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revoked_at: String,
    #[serde(rename = "revoked_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revoked_by: String,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "source_issuer")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_issuer: String,
    #[serde(rename = "source_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_subject: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum BootstrapBindingError {
    AccessUnavailable,
    AuditUnavailable,
    BootstrapConsumed,
    BootstrapExpired,
    InvalidRequest,
    NotActive,
    NotEnabled,
    NotFound,
    PermissionDenied,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SessionResponse {
    #[serde(rename = "credential")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: String,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
}

impl fmt::Debug for SessionResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("SessionResponse")
            .field("credential", &"<redacted>")
            .field("expires_at", &self.expires_at)
            .field("session_id", &self.session_id)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ExchangeSessionError {
    AccessUnavailable,
    AuditUnavailable,
    BootstrapConsumed,
    BootstrapExpired,
    InvalidRequest,
    NotActive,
    NotEnabled,
    NotFound,
    PermissionDenied,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadBindingError {
    AccessUnavailable,
    AuditUnavailable,
    BootstrapConsumed,
    BootstrapExpired,
    InvalidRequest,
    NotActive,
    NotEnabled,
    NotFound,
    PermissionDenied,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RevokeBindingRequest {
    #[serde(rename = "binding_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub binding_id: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RecoverRevocationError {
    AccessUnavailable,
    AuditUnavailable,
    BootstrapConsumed,
    BootstrapExpired,
    InvalidRequest,
    NotActive,
    NotEnabled,
    NotFound,
    PermissionDenied,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ResumeBindingRequest {
    #[serde(rename = "binding_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub binding_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ResumeBindingError {
    AccessUnavailable,
    AuditUnavailable,
    BootstrapConsumed,
    BootstrapExpired,
    InvalidRequest,
    NotActive,
    NotEnabled,
    NotFound,
    PermissionDenied,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq)]
pub enum RevokeBindingError {
    AccessUnavailable,
    AuditUnavailable,
    BootstrapConsumed,
    BootstrapExpired,
    InvalidRequest,
    NotActive,
    NotEnabled,
    NotFound,
    PermissionDenied,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct OperatorSessionBootstrapBinding;
impl RequestCapability for OperatorSessionBootstrapBinding {
    type Request = EmptyRequest;
    type Response = Binding;
    type DomainError = BootstrapBindingError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != BOOTSTRAP_BINDING_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OperatorSessionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).bootstrap_binding(context, request)
    }
}

#[derive(Debug)]
pub struct OperatorSessionExchangeSession;
impl RequestCapability for OperatorSessionExchangeSession {
    type Request = EmptyRequest;
    type Response = SessionResponse;
    type DomainError = ExchangeSessionError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != EXCHANGE_SESSION_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OperatorSessionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).exchange_session(context, request)
    }
}

#[derive(Debug)]
pub struct OperatorSessionReadBinding;
impl RequestCapability for OperatorSessionReadBinding {
    type Request = EmptyRequest;
    type Response = Binding;
    type DomainError = ReadBindingError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_BINDING_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OperatorSessionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read_binding(context, request)
    }
}

#[derive(Debug)]
pub struct OperatorSessionRecoverRevocation;
impl RequestCapability for OperatorSessionRecoverRevocation {
    type Request = RevokeBindingRequest;
    type Response = Binding;
    type DomainError = RecoverRevocationError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RECOVER_REVOCATION_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OperatorSessionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).recover_revocation(context, request)
    }
}

#[derive(Debug)]
pub struct OperatorSessionResumeBinding;
impl RequestCapability for OperatorSessionResumeBinding {
    type Request = ResumeBindingRequest;
    type Response = Binding;
    type DomainError = ResumeBindingError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RESUME_BINDING_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OperatorSessionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).resume_binding(context, request)
    }
}

#[derive(Debug)]
pub struct OperatorSessionRevokeBinding;
impl RequestCapability for OperatorSessionRevokeBinding {
    type Request = RevokeBindingRequest;
    type Response = Binding;
    type DomainError = RevokeBindingError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != REVOKE_BINDING_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OperatorSessionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).revoke_binding(context, request)
    }
}

impl serde::Serialize for BootstrapBindingError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AccessUnavailable => serializer.serialize_str("access_unavailable"),
            Self::AuditUnavailable => serializer.serialize_str("audit_unavailable"),
            Self::BootstrapConsumed => serializer.serialize_str("bootstrap_consumed"),
            Self::BootstrapExpired => serializer.serialize_str("bootstrap_expired"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotActive => serializer.serialize_str("not_active"),
            Self::NotEnabled => serializer.serialize_str("not_enabled"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for BootstrapBindingError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "access_unavailable" => Ok(Self::AccessUnavailable),
                "audit_unavailable" => Ok(Self::AuditUnavailable),
                "bootstrap_consumed" => Ok(Self::BootstrapConsumed),
                "bootstrap_expired" => Ok(Self::BootstrapExpired),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_active" => Ok(Self::NotActive),
                "not_enabled" => Ok(Self::NotEnabled),
                "not_found" => Ok(Self::NotFound),
                "permission_denied" => Ok(Self::PermissionDenied),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ExchangeSessionError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AccessUnavailable => serializer.serialize_str("access_unavailable"),
            Self::AuditUnavailable => serializer.serialize_str("audit_unavailable"),
            Self::BootstrapConsumed => serializer.serialize_str("bootstrap_consumed"),
            Self::BootstrapExpired => serializer.serialize_str("bootstrap_expired"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotActive => serializer.serialize_str("not_active"),
            Self::NotEnabled => serializer.serialize_str("not_enabled"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ExchangeSessionError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "access_unavailable" => Ok(Self::AccessUnavailable),
                "audit_unavailable" => Ok(Self::AuditUnavailable),
                "bootstrap_consumed" => Ok(Self::BootstrapConsumed),
                "bootstrap_expired" => Ok(Self::BootstrapExpired),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_active" => Ok(Self::NotActive),
                "not_enabled" => Ok(Self::NotEnabled),
                "not_found" => Ok(Self::NotFound),
                "permission_denied" => Ok(Self::PermissionDenied),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReadBindingError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AccessUnavailable => serializer.serialize_str("access_unavailable"),
            Self::AuditUnavailable => serializer.serialize_str("audit_unavailable"),
            Self::BootstrapConsumed => serializer.serialize_str("bootstrap_consumed"),
            Self::BootstrapExpired => serializer.serialize_str("bootstrap_expired"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotActive => serializer.serialize_str("not_active"),
            Self::NotEnabled => serializer.serialize_str("not_enabled"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadBindingError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "access_unavailable" => Ok(Self::AccessUnavailable),
                "audit_unavailable" => Ok(Self::AuditUnavailable),
                "bootstrap_consumed" => Ok(Self::BootstrapConsumed),
                "bootstrap_expired" => Ok(Self::BootstrapExpired),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_active" => Ok(Self::NotActive),
                "not_enabled" => Ok(Self::NotEnabled),
                "not_found" => Ok(Self::NotFound),
                "permission_denied" => Ok(Self::PermissionDenied),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RecoverRevocationError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AccessUnavailable => serializer.serialize_str("access_unavailable"),
            Self::AuditUnavailable => serializer.serialize_str("audit_unavailable"),
            Self::BootstrapConsumed => serializer.serialize_str("bootstrap_consumed"),
            Self::BootstrapExpired => serializer.serialize_str("bootstrap_expired"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotActive => serializer.serialize_str("not_active"),
            Self::NotEnabled => serializer.serialize_str("not_enabled"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RecoverRevocationError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "access_unavailable" => Ok(Self::AccessUnavailable),
                "audit_unavailable" => Ok(Self::AuditUnavailable),
                "bootstrap_consumed" => Ok(Self::BootstrapConsumed),
                "bootstrap_expired" => Ok(Self::BootstrapExpired),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_active" => Ok(Self::NotActive),
                "not_enabled" => Ok(Self::NotEnabled),
                "not_found" => Ok(Self::NotFound),
                "permission_denied" => Ok(Self::PermissionDenied),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ResumeBindingError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AccessUnavailable => serializer.serialize_str("access_unavailable"),
            Self::AuditUnavailable => serializer.serialize_str("audit_unavailable"),
            Self::BootstrapConsumed => serializer.serialize_str("bootstrap_consumed"),
            Self::BootstrapExpired => serializer.serialize_str("bootstrap_expired"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotActive => serializer.serialize_str("not_active"),
            Self::NotEnabled => serializer.serialize_str("not_enabled"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ResumeBindingError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "access_unavailable" => Ok(Self::AccessUnavailable),
                "audit_unavailable" => Ok(Self::AuditUnavailable),
                "bootstrap_consumed" => Ok(Self::BootstrapConsumed),
                "bootstrap_expired" => Ok(Self::BootstrapExpired),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_active" => Ok(Self::NotActive),
                "not_enabled" => Ok(Self::NotEnabled),
                "not_found" => Ok(Self::NotFound),
                "permission_denied" => Ok(Self::PermissionDenied),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RevokeBindingError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AccessUnavailable => serializer.serialize_str("access_unavailable"),
            Self::AuditUnavailable => serializer.serialize_str("audit_unavailable"),
            Self::BootstrapConsumed => serializer.serialize_str("bootstrap_consumed"),
            Self::BootstrapExpired => serializer.serialize_str("bootstrap_expired"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotActive => serializer.serialize_str("not_active"),
            Self::NotEnabled => serializer.serialize_str("not_enabled"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RevokeBindingError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "access_unavailable" => Ok(Self::AccessUnavailable),
                "audit_unavailable" => Ok(Self::AuditUnavailable),
                "bootstrap_consumed" => Ok(Self::BootstrapConsumed),
                "bootstrap_expired" => Ok(Self::BootstrapExpired),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_active" => Ok(Self::NotActive),
                "not_enabled" => Ok(Self::NotEnabled),
                "not_found" => Ok(Self::NotFound),
                "permission_denied" => Ok(Self::PermissionDenied),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_bootstrap_binding_request(value: &EmptyRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_bootstrap_binding_request(wire: &str) -> Result<EmptyRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_bootstrap_binding_response(value: &Binding) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_bootstrap_binding_response(wire: &str) -> Result<Binding, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_bootstrap_binding_error(value: &BootstrapBindingError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_bootstrap_binding_error(wire: &str) -> Result<BootstrapBindingError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_exchange_session_request(value: &EmptyRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_exchange_session_request(wire: &str) -> Result<EmptyRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_exchange_session_response(value: &SessionResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_exchange_session_response(wire: &str) -> Result<SessionResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_exchange_session_error(value: &ExchangeSessionError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_exchange_session_error(wire: &str) -> Result<ExchangeSessionError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_read_binding_request(value: &EmptyRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_binding_request(wire: &str) -> Result<EmptyRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_binding_response(value: &Binding) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_binding_response(wire: &str) -> Result<Binding, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_binding_error(value: &ReadBindingError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_binding_error(wire: &str) -> Result<ReadBindingError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_recover_revocation_request(value: &RevokeBindingRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_recover_revocation_request(wire: &str) -> Result<RevokeBindingRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_recover_revocation_response(value: &Binding) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_recover_revocation_response(wire: &str) -> Result<Binding, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_recover_revocation_error(value: &RecoverRevocationError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_recover_revocation_error(wire: &str) -> Result<RecoverRevocationError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_resume_binding_request(value: &ResumeBindingRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_resume_binding_request(wire: &str) -> Result<ResumeBindingRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_resume_binding_response(value: &Binding) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_resume_binding_response(wire: &str) -> Result<Binding, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_resume_binding_error(value: &ResumeBindingError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_resume_binding_error(wire: &str) -> Result<ResumeBindingError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_revoke_binding_request(value: &RevokeBindingRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_binding_request(wire: &str) -> Result<RevokeBindingRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_revoke_binding_response(value: &Binding) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_binding_response(wire: &str) -> Result<Binding, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_revoke_binding_error(value: &RevokeBindingError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_binding_error(wire: &str) -> Result<RevokeBindingError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoOperatorSessionBootstrapBindingResult {
    fn __lenso_into_result(self) -> Result<Result<Binding, BootstrapBindingError>, RuntimeFailure>;
}
impl __LensoIntoOperatorSessionBootstrapBindingResult for Result<Binding, BootstrapBindingError> {
    fn __lenso_into_result(self) -> Result<Result<Binding, BootstrapBindingError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOperatorSessionBootstrapBindingResult for Result<Result<Binding, BootstrapBindingError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<Binding, BootstrapBindingError>, RuntimeFailure> { self }
}
impl __LensoIntoOperatorSessionBootstrapBindingResult for Result<Binding, lenso_plugin_authoring::PluginError<BootstrapBindingError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<Binding, BootstrapBindingError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOperatorSessionBootstrapBindingResult for Result<Binding, OperatorSessionBootstrapBindingInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<Binding, BootstrapBindingError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OperatorSessionBootstrapBindingInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OperatorSessionBootstrapBindingInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOperatorSessionExchangeSessionResult {
    fn __lenso_into_result(self) -> Result<Result<SessionResponse, ExchangeSessionError>, RuntimeFailure>;
}
impl __LensoIntoOperatorSessionExchangeSessionResult for Result<SessionResponse, ExchangeSessionError> {
    fn __lenso_into_result(self) -> Result<Result<SessionResponse, ExchangeSessionError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOperatorSessionExchangeSessionResult for Result<Result<SessionResponse, ExchangeSessionError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<SessionResponse, ExchangeSessionError>, RuntimeFailure> { self }
}
impl __LensoIntoOperatorSessionExchangeSessionResult for Result<SessionResponse, lenso_plugin_authoring::PluginError<ExchangeSessionError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<SessionResponse, ExchangeSessionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOperatorSessionExchangeSessionResult for Result<SessionResponse, OperatorSessionExchangeSessionInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<SessionResponse, ExchangeSessionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OperatorSessionExchangeSessionInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OperatorSessionExchangeSessionInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOperatorSessionReadBindingResult {
    fn __lenso_into_result(self) -> Result<Result<Binding, ReadBindingError>, RuntimeFailure>;
}
impl __LensoIntoOperatorSessionReadBindingResult for Result<Binding, ReadBindingError> {
    fn __lenso_into_result(self) -> Result<Result<Binding, ReadBindingError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOperatorSessionReadBindingResult for Result<Result<Binding, ReadBindingError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<Binding, ReadBindingError>, RuntimeFailure> { self }
}
impl __LensoIntoOperatorSessionReadBindingResult for Result<Binding, lenso_plugin_authoring::PluginError<ReadBindingError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<Binding, ReadBindingError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOperatorSessionReadBindingResult for Result<Binding, OperatorSessionReadBindingInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<Binding, ReadBindingError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OperatorSessionReadBindingInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OperatorSessionReadBindingInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOperatorSessionRecoverRevocationResult {
    fn __lenso_into_result(self) -> Result<Result<Binding, RecoverRevocationError>, RuntimeFailure>;
}
impl __LensoIntoOperatorSessionRecoverRevocationResult for Result<Binding, RecoverRevocationError> {
    fn __lenso_into_result(self) -> Result<Result<Binding, RecoverRevocationError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOperatorSessionRecoverRevocationResult for Result<Result<Binding, RecoverRevocationError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<Binding, RecoverRevocationError>, RuntimeFailure> { self }
}
impl __LensoIntoOperatorSessionRecoverRevocationResult for Result<Binding, lenso_plugin_authoring::PluginError<RecoverRevocationError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<Binding, RecoverRevocationError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOperatorSessionRecoverRevocationResult for Result<Binding, OperatorSessionRecoverRevocationInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<Binding, RecoverRevocationError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OperatorSessionRecoverRevocationInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OperatorSessionRecoverRevocationInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOperatorSessionResumeBindingResult {
    fn __lenso_into_result(self) -> Result<Result<Binding, ResumeBindingError>, RuntimeFailure>;
}
impl __LensoIntoOperatorSessionResumeBindingResult for Result<Binding, ResumeBindingError> {
    fn __lenso_into_result(self) -> Result<Result<Binding, ResumeBindingError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOperatorSessionResumeBindingResult for Result<Result<Binding, ResumeBindingError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<Binding, ResumeBindingError>, RuntimeFailure> { self }
}
impl __LensoIntoOperatorSessionResumeBindingResult for Result<Binding, lenso_plugin_authoring::PluginError<ResumeBindingError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<Binding, ResumeBindingError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOperatorSessionResumeBindingResult for Result<Binding, OperatorSessionResumeBindingInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<Binding, ResumeBindingError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OperatorSessionResumeBindingInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OperatorSessionResumeBindingInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOperatorSessionRevokeBindingResult {
    fn __lenso_into_result(self) -> Result<Result<Binding, RevokeBindingError>, RuntimeFailure>;
}
impl __LensoIntoOperatorSessionRevokeBindingResult for Result<Binding, RevokeBindingError> {
    fn __lenso_into_result(self) -> Result<Result<Binding, RevokeBindingError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOperatorSessionRevokeBindingResult for Result<Result<Binding, RevokeBindingError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<Binding, RevokeBindingError>, RuntimeFailure> { self }
}
impl __LensoIntoOperatorSessionRevokeBindingResult for Result<Binding, lenso_plugin_authoring::PluginError<RevokeBindingError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<Binding, RevokeBindingError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOperatorSessionRevokeBindingResult for Result<Binding, OperatorSessionRevokeBindingInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<Binding, RevokeBindingError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OperatorSessionRevokeBindingInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OperatorSessionRevokeBindingInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait OperatorSessionProvider: fmt::Debug + 'static {
    fn bootstrap_binding(&self, context: InvocationContext, request: EmptyRequest) -> NativeRequestFuture<OperatorSessionBootstrapBinding>;
    fn exchange_session(&self, context: InvocationContext, request: EmptyRequest) -> NativeRequestFuture<OperatorSessionExchangeSession>;
    fn read_binding(&self, context: InvocationContext, request: EmptyRequest) -> NativeRequestFuture<OperatorSessionReadBinding>;
    fn recover_revocation(&self, context: InvocationContext, request: RevokeBindingRequest) -> NativeRequestFuture<OperatorSessionRecoverRevocation>;
    fn resume_binding(&self, context: InvocationContext, request: ResumeBindingRequest) -> NativeRequestFuture<OperatorSessionResumeBinding>;
    fn revoke_binding(&self, context: InvocationContext, request: RevokeBindingRequest) -> NativeRequestFuture<OperatorSessionRevokeBinding>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_operator_session {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportOperatorSession;
        impl $crate::OperatorSessionProvider for $plugin {
        fn bootstrap_binding(&self, context: __LensoNativeSupportOperatorSession::InvocationContext, request: $crate::EmptyRequest) -> __LensoNativeSupportOperatorSession::NativeRequestFuture<$crate::OperatorSessionBootstrapBinding> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::bootstrap_binding(&plugin, context, request).await;
                $crate::__LensoIntoOperatorSessionBootstrapBindingResult::__lenso_into_result(result)
            })
        }
        fn exchange_session(&self, context: __LensoNativeSupportOperatorSession::InvocationContext, request: $crate::EmptyRequest) -> __LensoNativeSupportOperatorSession::NativeRequestFuture<$crate::OperatorSessionExchangeSession> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::exchange_session(&plugin, context, request).await;
                $crate::__LensoIntoOperatorSessionExchangeSessionResult::__lenso_into_result(result)
            })
        }
        fn read_binding(&self, context: __LensoNativeSupportOperatorSession::InvocationContext, request: $crate::EmptyRequest) -> __LensoNativeSupportOperatorSession::NativeRequestFuture<$crate::OperatorSessionReadBinding> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::read_binding(&plugin, context, request).await;
                $crate::__LensoIntoOperatorSessionReadBindingResult::__lenso_into_result(result)
            })
        }
        fn recover_revocation(&self, context: __LensoNativeSupportOperatorSession::InvocationContext, request: $crate::RevokeBindingRequest) -> __LensoNativeSupportOperatorSession::NativeRequestFuture<$crate::OperatorSessionRecoverRevocation> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::recover_revocation(&plugin, context, request).await;
                $crate::__LensoIntoOperatorSessionRecoverRevocationResult::__lenso_into_result(result)
            })
        }
        fn resume_binding(&self, context: __LensoNativeSupportOperatorSession::InvocationContext, request: $crate::ResumeBindingRequest) -> __LensoNativeSupportOperatorSession::NativeRequestFuture<$crate::OperatorSessionResumeBinding> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::resume_binding(&plugin, context, request).await;
                $crate::__LensoIntoOperatorSessionResumeBindingResult::__lenso_into_result(result)
            })
        }
        fn revoke_binding(&self, context: __LensoNativeSupportOperatorSession::InvocationContext, request: $crate::RevokeBindingRequest) -> __LensoNativeSupportOperatorSession::NativeRequestFuture<$crate::OperatorSessionRevokeBinding> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::revoke_binding(&plugin, context, request).await;
                $crate::__LensoIntoOperatorSessionRevokeBindingResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_operator_session {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportOperatorSession;
        impl $crate::OperatorSessionProvider for $object {
        fn bootstrap_binding(&self, context: __LensoNativeSupportOperatorSession::InvocationContext, request: $crate::EmptyRequest) -> __LensoNativeSupportOperatorSession::NativeRequestFuture<$crate::OperatorSessionBootstrapBinding> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::bootstrap_binding(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoOperatorSessionBootstrapBindingResult::__lenso_into_result(result)
            })
        }
        fn exchange_session(&self, context: __LensoNativeSupportOperatorSession::InvocationContext, request: $crate::EmptyRequest) -> __LensoNativeSupportOperatorSession::NativeRequestFuture<$crate::OperatorSessionExchangeSession> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::exchange_session(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoOperatorSessionExchangeSessionResult::__lenso_into_result(result)
            })
        }
        fn read_binding(&self, context: __LensoNativeSupportOperatorSession::InvocationContext, request: $crate::EmptyRequest) -> __LensoNativeSupportOperatorSession::NativeRequestFuture<$crate::OperatorSessionReadBinding> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::read_binding(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoOperatorSessionReadBindingResult::__lenso_into_result(result)
            })
        }
        fn recover_revocation(&self, context: __LensoNativeSupportOperatorSession::InvocationContext, request: $crate::RevokeBindingRequest) -> __LensoNativeSupportOperatorSession::NativeRequestFuture<$crate::OperatorSessionRecoverRevocation> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::recover_revocation(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoOperatorSessionRecoverRevocationResult::__lenso_into_result(result)
            })
        }
        fn resume_binding(&self, context: __LensoNativeSupportOperatorSession::InvocationContext, request: $crate::ResumeBindingRequest) -> __LensoNativeSupportOperatorSession::NativeRequestFuture<$crate::OperatorSessionResumeBinding> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::resume_binding(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoOperatorSessionResumeBindingResult::__lenso_into_result(result)
            })
        }
        fn revoke_binding(&self, context: __LensoNativeSupportOperatorSession::InvocationContext, request: $crate::RevokeBindingRequest) -> __LensoNativeSupportOperatorSession::NativeRequestFuture<$crate::OperatorSessionRevokeBinding> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::revoke_binding(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoOperatorSessionRevokeBindingResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_operator_session {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportOperatorSession;
        impl $crate::OperatorSessionProvider for $object {
        fn bootstrap_binding(&self, context: __LensoNativeSupportOperatorSession::InvocationContext, request: $crate::EmptyRequest) -> __LensoNativeSupportOperatorSession::NativeRequestFuture<$crate::OperatorSessionBootstrapBinding> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::OperatorSessionProvider>::bootstrap_binding(plugin.as_ref(), context, request).await
            })
        }
        fn exchange_session(&self, context: __LensoNativeSupportOperatorSession::InvocationContext, request: $crate::EmptyRequest) -> __LensoNativeSupportOperatorSession::NativeRequestFuture<$crate::OperatorSessionExchangeSession> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::OperatorSessionProvider>::exchange_session(plugin.as_ref(), context, request).await
            })
        }
        fn read_binding(&self, context: __LensoNativeSupportOperatorSession::InvocationContext, request: $crate::EmptyRequest) -> __LensoNativeSupportOperatorSession::NativeRequestFuture<$crate::OperatorSessionReadBinding> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::OperatorSessionProvider>::read_binding(plugin.as_ref(), context, request).await
            })
        }
        fn recover_revocation(&self, context: __LensoNativeSupportOperatorSession::InvocationContext, request: $crate::RevokeBindingRequest) -> __LensoNativeSupportOperatorSession::NativeRequestFuture<$crate::OperatorSessionRecoverRevocation> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::OperatorSessionProvider>::recover_revocation(plugin.as_ref(), context, request).await
            })
        }
        fn resume_binding(&self, context: __LensoNativeSupportOperatorSession::InvocationContext, request: $crate::ResumeBindingRequest) -> __LensoNativeSupportOperatorSession::NativeRequestFuture<$crate::OperatorSessionResumeBinding> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::OperatorSessionProvider>::resume_binding(plugin.as_ref(), context, request).await
            })
        }
        fn revoke_binding(&self, context: __LensoNativeSupportOperatorSession::InvocationContext, request: $crate::RevokeBindingRequest) -> __LensoNativeSupportOperatorSession::NativeRequestFuture<$crate::OperatorSessionRevokeBinding> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::OperatorSessionProvider>::revoke_binding(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct OperatorSessionRequestEndpoint { provider: Rc<dyn OperatorSessionProvider> }

#[derive(Debug)]
pub struct OperatorSessionEndpoint<P: OperatorSessionProvider> { provider: Rc<P>, request_endpoint: OperatorSessionRequestEndpoint }
impl<P: OperatorSessionProvider> OperatorSessionEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn OperatorSessionProvider> = provider.clone();
        Self { provider, request_endpoint: OperatorSessionRequestEndpoint { provider: request_provider } }
    }
}

impl<P: OperatorSessionProvider> NativeRequestEndpoint for OperatorSessionEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        BOOTSTRAP_BINDING_OPERATION,
        EXCHANGE_SESSION_OPERATION,
        READ_BINDING_OPERATION,
        RECOVER_REVOCATION_OPERATION,
        RESUME_BINDING_OPERATION,
        REVOKE_BINDING_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            BOOTSTRAP_BINDING_OPERATION => {
                let Ok(request) = request.downcast::<EmptyRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).bootstrap_binding(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            EXCHANGE_SESSION_OPERATION => {
                let Ok(request) = request.downcast::<EmptyRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).exchange_session(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            READ_BINDING_OPERATION => {
                let Ok(request) = request.downcast::<EmptyRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read_binding(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RECOVER_REVOCATION_OPERATION => {
                let Ok(request) = request.downcast::<RevokeBindingRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).recover_revocation(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RESUME_BINDING_OPERATION => {
                let Ok(request) = request.downcast::<ResumeBindingRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).resume_binding(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            REVOKE_BINDING_OPERATION => {
                let Ok(request) = request.downcast::<RevokeBindingRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).revoke_binding(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_operator_session {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::OperatorSessionEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_operator_session {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_operator_session!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct OperatorSessionClient {
    bootstrap_binding: NativeRequestHandle<OperatorSessionBootstrapBinding>,
    exchange_session: NativeRequestHandle<OperatorSessionExchangeSession>,
    read_binding: NativeRequestHandle<OperatorSessionReadBinding>,
    recover_revocation: NativeRequestHandle<OperatorSessionRecoverRevocation>,
    resume_binding: NativeRequestHandle<OperatorSessionResumeBinding>,
    revoke_binding: NativeRequestHandle<OperatorSessionRevokeBinding>,
}
impl OperatorSessionClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn bootstrap_binding(&self, request: EmptyRequest) -> Result<Binding, OperatorSessionBootstrapBindingInvocationError> {
        self.bootstrap_binding.invoke(BOOTSTRAP_BINDING_OPERATION, request).await
            .map_err(OperatorSessionBootstrapBindingInvocationError::Runtime)?
            .map_err(OperatorSessionBootstrapBindingInvocationError::Domain)
    }

    pub async fn bootstrap_binding_with_context(&self, context: InvocationContext, request: EmptyRequest) -> Result<Binding, OperatorSessionBootstrapBindingInvocationError> {
        self.bootstrap_binding.invoke_with_context(BOOTSTRAP_BINDING_OPERATION, context, request).await
            .map_err(OperatorSessionBootstrapBindingInvocationError::Runtime)?
            .map_err(OperatorSessionBootstrapBindingInvocationError::Domain)
    }

    pub async fn exchange_session(&self, request: EmptyRequest) -> Result<SessionResponse, OperatorSessionExchangeSessionInvocationError> {
        self.exchange_session.invoke(EXCHANGE_SESSION_OPERATION, request).await
            .map_err(OperatorSessionExchangeSessionInvocationError::Runtime)?
            .map_err(OperatorSessionExchangeSessionInvocationError::Domain)
    }

    pub async fn exchange_session_with_context(&self, context: InvocationContext, request: EmptyRequest) -> Result<SessionResponse, OperatorSessionExchangeSessionInvocationError> {
        self.exchange_session.invoke_with_context(EXCHANGE_SESSION_OPERATION, context, request).await
            .map_err(OperatorSessionExchangeSessionInvocationError::Runtime)?
            .map_err(OperatorSessionExchangeSessionInvocationError::Domain)
    }

    pub async fn read_binding(&self, request: EmptyRequest) -> Result<Binding, OperatorSessionReadBindingInvocationError> {
        self.read_binding.invoke(READ_BINDING_OPERATION, request).await
            .map_err(OperatorSessionReadBindingInvocationError::Runtime)?
            .map_err(OperatorSessionReadBindingInvocationError::Domain)
    }

    pub async fn read_binding_with_context(&self, context: InvocationContext, request: EmptyRequest) -> Result<Binding, OperatorSessionReadBindingInvocationError> {
        self.read_binding.invoke_with_context(READ_BINDING_OPERATION, context, request).await
            .map_err(OperatorSessionReadBindingInvocationError::Runtime)?
            .map_err(OperatorSessionReadBindingInvocationError::Domain)
    }

    pub async fn recover_revocation(&self, request: RevokeBindingRequest) -> Result<Binding, OperatorSessionRecoverRevocationInvocationError> {
        self.recover_revocation.invoke(RECOVER_REVOCATION_OPERATION, request).await
            .map_err(OperatorSessionRecoverRevocationInvocationError::Runtime)?
            .map_err(OperatorSessionRecoverRevocationInvocationError::Domain)
    }

    pub async fn recover_revocation_with_context(&self, context: InvocationContext, request: RevokeBindingRequest) -> Result<Binding, OperatorSessionRecoverRevocationInvocationError> {
        self.recover_revocation.invoke_with_context(RECOVER_REVOCATION_OPERATION, context, request).await
            .map_err(OperatorSessionRecoverRevocationInvocationError::Runtime)?
            .map_err(OperatorSessionRecoverRevocationInvocationError::Domain)
    }

    pub async fn resume_binding(&self, request: ResumeBindingRequest) -> Result<Binding, OperatorSessionResumeBindingInvocationError> {
        self.resume_binding.invoke(RESUME_BINDING_OPERATION, request).await
            .map_err(OperatorSessionResumeBindingInvocationError::Runtime)?
            .map_err(OperatorSessionResumeBindingInvocationError::Domain)
    }

    pub async fn resume_binding_with_context(&self, context: InvocationContext, request: ResumeBindingRequest) -> Result<Binding, OperatorSessionResumeBindingInvocationError> {
        self.resume_binding.invoke_with_context(RESUME_BINDING_OPERATION, context, request).await
            .map_err(OperatorSessionResumeBindingInvocationError::Runtime)?
            .map_err(OperatorSessionResumeBindingInvocationError::Domain)
    }

    pub async fn revoke_binding(&self, request: RevokeBindingRequest) -> Result<Binding, OperatorSessionRevokeBindingInvocationError> {
        self.revoke_binding.invoke(REVOKE_BINDING_OPERATION, request).await
            .map_err(OperatorSessionRevokeBindingInvocationError::Runtime)?
            .map_err(OperatorSessionRevokeBindingInvocationError::Domain)
    }

    pub async fn revoke_binding_with_context(&self, context: InvocationContext, request: RevokeBindingRequest) -> Result<Binding, OperatorSessionRevokeBindingInvocationError> {
        self.revoke_binding.invoke_with_context(REVOKE_BINDING_OPERATION, context, request).await
            .map_err(OperatorSessionRevokeBindingInvocationError::Runtime)?
            .map_err(OperatorSessionRevokeBindingInvocationError::Domain)
    }
}

impl CapabilityClient for OperatorSessionClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            bootstrap_binding: dependencies.one::<OperatorSessionBootstrapBinding>()?,
            exchange_session: dependencies.one::<OperatorSessionExchangeSession>()?,
            read_binding: dependencies.one::<OperatorSessionReadBinding>()?,
            recover_revocation: dependencies.one::<OperatorSessionRecoverRevocation>()?,
            resume_binding: dependencies.one::<OperatorSessionResumeBinding>()?,
            revoke_binding: dependencies.one::<OperatorSessionRevokeBinding>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for OperatorSessionClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    bootstrap_binding: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OperatorSessionBootstrapBinding>()?,
                    exchange_session: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OperatorSessionExchangeSession>()?,
                    read_binding: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OperatorSessionReadBinding>()?,
                    recover_revocation: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OperatorSessionRecoverRevocation>()?,
                    resume_binding: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OperatorSessionResumeBinding>()?,
                    revoke_binding: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OperatorSessionRevokeBinding>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum OperatorSessionBootstrapBindingInvocationError {
    Domain(BootstrapBindingError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OperatorSessionExchangeSessionInvocationError {
    Domain(ExchangeSessionError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OperatorSessionReadBindingInvocationError {
    Domain(ReadBindingError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OperatorSessionRecoverRevocationInvocationError {
    Domain(RecoverRevocationError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OperatorSessionResumeBindingInvocationError {
    Domain(ResumeBindingError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OperatorSessionRevokeBindingInvocationError {
    Domain(RevokeBindingError),
    Runtime(RuntimeFailure),
}
