// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.auth.human-api-token@1";
pub const DESCRIPTOR_VERSION: &str = "1.1.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:d0bb0048d93a476ad2fbb4765abb2646be567409e67fbb37553427c6cb50a611";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const HUMAN_API_TOKEN_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const HUMAN_API_TOKEN_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const HUMAN_API_TOKEN_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const HUMAN_API_TOKEN_CONTRACT: CapabilityReference<HumanApiTokenClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_human_api_token { () => { "{\"capability_id\":\"lenso.auth.human-api-token@1\",\"descriptor_version\":\"1.1.0\",\"operations\":[\"issue\",\"list\",\"receipt\",\"revoke\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_human_api_token_client {
    () => { "{\"capability_id\":\"lenso.auth.human-api-token@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.human-api-token@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_human_api_token_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.human-api-token@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_human_api_token_client {
    () => { "{\"capability_id\":\"lenso.auth.human-api-token@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.human-api-token@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"many\"}") };
}

pub const ISSUE_OPERATION: &str = "issue";
pub const LIST_OPERATION: &str = "list";
pub const RECEIPT_OPERATION: &str = "receipt";
pub const REVOKE_OPERATION: &str = "revoke";

pub use lenso_contract_runtime::{OptionalValue, Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct IssueRequest {
    #[serde(rename = "deployment")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub deployment: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "permissions")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub permissions: Vec<String>,
    #[serde(rename = "resource_scopes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resource_scopes: Vec<ResourceScope>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ResourceScope {
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct IssueResponse {
    #[serde(rename = "credential")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential: CredentialMetadata,
    #[serde(rename = "replayed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub replayed: bool,
    #[serde(rename = "token")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub token: OptionalValue<String>,
}

impl fmt::Debug for IssueResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("IssueResponse")
            .field("credential", &self.credential)
            .field("replayed", &self.replayed)
            .field("token", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CredentialMetadata {
    #[serde(rename = "active")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub active: bool,
    #[serde(rename = "created_at")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub created_at: OptionalValue<Timestamp>,
    #[serde(rename = "credential_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential_id: String,
    #[serde(rename = "deployment")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub deployment: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "last_used_at")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub last_used_at: OptionalValue<Timestamp>,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "permissions")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub permissions: Vec<String>,
    #[serde(rename = "resource_scopes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resource_scopes: Vec<ResourceScope>,
    #[serde(rename = "revoked_at")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub revoked_at: OptionalValue<Timestamp>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum IssueError {
    Conflict,
    InvalidRequest,
    PermissionDenied,
    UnsupportedProfile,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListRequest {
    #[serde(rename = "after_credential_id")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub after_credential_id: OptionalValue<String>,
    #[serde(rename = "deployment")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub deployment: String,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListResponse {
    #[serde(rename = "credentials")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credentials: Vec<CredentialMetadata>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListError {
    InvalidRequest,
    PermissionDenied,
    UnsupportedProfile,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReceiptRequest {
    #[serde(rename = "deployment")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub deployment: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReceiptResponse {
    #[serde(rename = "credential")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub credential: OptionalValue<CredentialMetadata>,
    #[serde(rename = "found")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub found: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReceiptError {
    InvalidRequest,
    PermissionDenied,
    UnsupportedProfile,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RevokeRequest {
    #[serde(rename = "credential_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential_id: String,
    #[serde(rename = "deployment")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub deployment: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RevokeResponse {
    #[serde(rename = "revoked")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revoked: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RevokeError {
    InvalidRequest,
    NotFound,
    PermissionDenied,
    UnsupportedProfile,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct HumanApiTokenIssue;
impl RequestCapability for HumanApiTokenIssue {
    type Request = IssueRequest;
    type Response = IssueResponse;
    type DomainError = IssueError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != ISSUE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<HumanApiTokenRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).issue(context, request)
    }
}

#[derive(Debug)]
pub struct HumanApiTokenList;
impl RequestCapability for HumanApiTokenList {
    type Request = ListRequest;
    type Response = ListResponse;
    type DomainError = ListError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<HumanApiTokenRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list(context, request)
    }
}

#[derive(Debug)]
pub struct HumanApiTokenReceipt;
impl RequestCapability for HumanApiTokenReceipt {
    type Request = ReceiptRequest;
    type Response = ReceiptResponse;
    type DomainError = ReceiptError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RECEIPT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<HumanApiTokenRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).receipt(context, request)
    }
}

#[derive(Debug)]
pub struct HumanApiTokenRevoke;
impl RequestCapability for HumanApiTokenRevoke {
    type Request = RevokeRequest;
    type Response = RevokeResponse;
    type DomainError = RevokeError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != REVOKE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<HumanApiTokenRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).revoke(context, request)
    }
}

impl serde::Serialize for IssueError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::UnsupportedProfile => serializer.serialize_str("unsupported_profile"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for IssueError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "permission_denied" => Ok(Self::PermissionDenied),
                "unsupported_profile" => Ok(Self::UnsupportedProfile),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ListError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::UnsupportedProfile => serializer.serialize_str("unsupported_profile"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_request" => Ok(Self::InvalidRequest),
                "permission_denied" => Ok(Self::PermissionDenied),
                "unsupported_profile" => Ok(Self::UnsupportedProfile),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReceiptError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::UnsupportedProfile => serializer.serialize_str("unsupported_profile"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReceiptError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_request" => Ok(Self::InvalidRequest),
                "permission_denied" => Ok(Self::PermissionDenied),
                "unsupported_profile" => Ok(Self::UnsupportedProfile),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RevokeError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::UnsupportedProfile => serializer.serialize_str("unsupported_profile"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RevokeError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_found" => Ok(Self::NotFound),
                "permission_denied" => Ok(Self::PermissionDenied),
                "unsupported_profile" => Ok(Self::UnsupportedProfile),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_issue_request(value: &IssueRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_issue_request(wire: &str) -> Result<IssueRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_issue_response(value: &IssueResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_issue_response(wire: &str) -> Result<IssueResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_issue_error(value: &IssueError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_issue_error(wire: &str) -> Result<IssueError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_list_request(value: &ListRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_request(wire: &str) -> Result<ListRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_response(value: &ListResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_response(wire: &str) -> Result<ListResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_error(value: &ListError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_error(wire: &str) -> Result<ListError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_receipt_request(value: &ReceiptRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_receipt_request(wire: &str) -> Result<ReceiptRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_receipt_response(value: &ReceiptResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_receipt_response(wire: &str) -> Result<ReceiptResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_receipt_error(value: &ReceiptError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_receipt_error(wire: &str) -> Result<ReceiptError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_revoke_request(value: &RevokeRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_request(wire: &str) -> Result<RevokeRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_revoke_response(value: &RevokeResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_response(wire: &str) -> Result<RevokeResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_revoke_error(value: &RevokeError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_error(wire: &str) -> Result<RevokeError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoHumanApiTokenIssueResult {
    fn __lenso_into_result(self) -> Result<Result<IssueResponse, IssueError>, RuntimeFailure>;
}
impl __LensoIntoHumanApiTokenIssueResult for Result<IssueResponse, IssueError> {
    fn __lenso_into_result(self) -> Result<Result<IssueResponse, IssueError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoHumanApiTokenIssueResult for Result<Result<IssueResponse, IssueError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<IssueResponse, IssueError>, RuntimeFailure> { self }
}
impl __LensoIntoHumanApiTokenIssueResult for Result<IssueResponse, lenso_plugin_authoring::PluginError<IssueError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<IssueResponse, IssueError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoHumanApiTokenIssueResult for Result<IssueResponse, HumanApiTokenIssueInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<IssueResponse, IssueError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(HumanApiTokenIssueInvocationError::Domain(error)) => Ok(Err(error)),
            Err(HumanApiTokenIssueInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoHumanApiTokenListResult {
    fn __lenso_into_result(self) -> Result<Result<ListResponse, ListError>, RuntimeFailure>;
}
impl __LensoIntoHumanApiTokenListResult for Result<ListResponse, ListError> {
    fn __lenso_into_result(self) -> Result<Result<ListResponse, ListError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoHumanApiTokenListResult for Result<Result<ListResponse, ListError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListResponse, ListError>, RuntimeFailure> { self }
}
impl __LensoIntoHumanApiTokenListResult for Result<ListResponse, lenso_plugin_authoring::PluginError<ListError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListResponse, ListError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoHumanApiTokenListResult for Result<ListResponse, HumanApiTokenListInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListResponse, ListError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(HumanApiTokenListInvocationError::Domain(error)) => Ok(Err(error)),
            Err(HumanApiTokenListInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoHumanApiTokenReceiptResult {
    fn __lenso_into_result(self) -> Result<Result<ReceiptResponse, ReceiptError>, RuntimeFailure>;
}
impl __LensoIntoHumanApiTokenReceiptResult for Result<ReceiptResponse, ReceiptError> {
    fn __lenso_into_result(self) -> Result<Result<ReceiptResponse, ReceiptError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoHumanApiTokenReceiptResult for Result<Result<ReceiptResponse, ReceiptError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReceiptResponse, ReceiptError>, RuntimeFailure> { self }
}
impl __LensoIntoHumanApiTokenReceiptResult for Result<ReceiptResponse, lenso_plugin_authoring::PluginError<ReceiptError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReceiptResponse, ReceiptError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoHumanApiTokenReceiptResult for Result<ReceiptResponse, HumanApiTokenReceiptInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReceiptResponse, ReceiptError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(HumanApiTokenReceiptInvocationError::Domain(error)) => Ok(Err(error)),
            Err(HumanApiTokenReceiptInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoHumanApiTokenRevokeResult {
    fn __lenso_into_result(self) -> Result<Result<RevokeResponse, RevokeError>, RuntimeFailure>;
}
impl __LensoIntoHumanApiTokenRevokeResult for Result<RevokeResponse, RevokeError> {
    fn __lenso_into_result(self) -> Result<Result<RevokeResponse, RevokeError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoHumanApiTokenRevokeResult for Result<Result<RevokeResponse, RevokeError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<RevokeResponse, RevokeError>, RuntimeFailure> { self }
}
impl __LensoIntoHumanApiTokenRevokeResult for Result<RevokeResponse, lenso_plugin_authoring::PluginError<RevokeError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<RevokeResponse, RevokeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoHumanApiTokenRevokeResult for Result<RevokeResponse, HumanApiTokenRevokeInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<RevokeResponse, RevokeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(HumanApiTokenRevokeInvocationError::Domain(error)) => Ok(Err(error)),
            Err(HumanApiTokenRevokeInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait HumanApiTokenProvider: fmt::Debug + 'static {
    fn issue(&self, context: InvocationContext, request: IssueRequest) -> NativeRequestFuture<HumanApiTokenIssue>;
    fn list(&self, context: InvocationContext, request: ListRequest) -> NativeRequestFuture<HumanApiTokenList>;
    fn receipt(&self, context: InvocationContext, request: ReceiptRequest) -> NativeRequestFuture<HumanApiTokenReceipt>;
    fn revoke(&self, context: InvocationContext, request: RevokeRequest) -> NativeRequestFuture<HumanApiTokenRevoke>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_human_api_token {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportHumanApiToken;
        impl $crate::HumanApiTokenProvider for $plugin {
        fn issue(&self, context: __LensoNativeSupportHumanApiToken::InvocationContext, request: $crate::IssueRequest) -> __LensoNativeSupportHumanApiToken::NativeRequestFuture<$crate::HumanApiTokenIssue> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::issue(&plugin, context, request).await;
                $crate::__LensoIntoHumanApiTokenIssueResult::__lenso_into_result(result)
            })
        }
        fn list(&self, context: __LensoNativeSupportHumanApiToken::InvocationContext, request: $crate::ListRequest) -> __LensoNativeSupportHumanApiToken::NativeRequestFuture<$crate::HumanApiTokenList> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list(&plugin, context, request).await;
                $crate::__LensoIntoHumanApiTokenListResult::__lenso_into_result(result)
            })
        }
        fn receipt(&self, context: __LensoNativeSupportHumanApiToken::InvocationContext, request: $crate::ReceiptRequest) -> __LensoNativeSupportHumanApiToken::NativeRequestFuture<$crate::HumanApiTokenReceipt> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::receipt(&plugin, context, request).await;
                $crate::__LensoIntoHumanApiTokenReceiptResult::__lenso_into_result(result)
            })
        }
        fn revoke(&self, context: __LensoNativeSupportHumanApiToken::InvocationContext, request: $crate::RevokeRequest) -> __LensoNativeSupportHumanApiToken::NativeRequestFuture<$crate::HumanApiTokenRevoke> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::revoke(&plugin, context, request).await;
                $crate::__LensoIntoHumanApiTokenRevokeResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_human_api_token {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportHumanApiToken;
        impl $crate::HumanApiTokenProvider for $object {
        fn issue(&self, context: __LensoNativeSupportHumanApiToken::InvocationContext, request: $crate::IssueRequest) -> __LensoNativeSupportHumanApiToken::NativeRequestFuture<$crate::HumanApiTokenIssue> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::issue(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoHumanApiTokenIssueResult::__lenso_into_result(result)
            })
        }
        fn list(&self, context: __LensoNativeSupportHumanApiToken::InvocationContext, request: $crate::ListRequest) -> __LensoNativeSupportHumanApiToken::NativeRequestFuture<$crate::HumanApiTokenList> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::list(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoHumanApiTokenListResult::__lenso_into_result(result)
            })
        }
        fn receipt(&self, context: __LensoNativeSupportHumanApiToken::InvocationContext, request: $crate::ReceiptRequest) -> __LensoNativeSupportHumanApiToken::NativeRequestFuture<$crate::HumanApiTokenReceipt> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::receipt(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoHumanApiTokenReceiptResult::__lenso_into_result(result)
            })
        }
        fn revoke(&self, context: __LensoNativeSupportHumanApiToken::InvocationContext, request: $crate::RevokeRequest) -> __LensoNativeSupportHumanApiToken::NativeRequestFuture<$crate::HumanApiTokenRevoke> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::revoke(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoHumanApiTokenRevokeResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_human_api_token {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportHumanApiToken;
        impl $crate::HumanApiTokenProvider for $object {
        fn issue(&self, context: __LensoNativeSupportHumanApiToken::InvocationContext, request: $crate::IssueRequest) -> __LensoNativeSupportHumanApiToken::NativeRequestFuture<$crate::HumanApiTokenIssue> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::HumanApiTokenProvider>::issue(plugin.as_ref(), context, request).await
            })
        }
        fn list(&self, context: __LensoNativeSupportHumanApiToken::InvocationContext, request: $crate::ListRequest) -> __LensoNativeSupportHumanApiToken::NativeRequestFuture<$crate::HumanApiTokenList> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::HumanApiTokenProvider>::list(plugin.as_ref(), context, request).await
            })
        }
        fn receipt(&self, context: __LensoNativeSupportHumanApiToken::InvocationContext, request: $crate::ReceiptRequest) -> __LensoNativeSupportHumanApiToken::NativeRequestFuture<$crate::HumanApiTokenReceipt> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::HumanApiTokenProvider>::receipt(plugin.as_ref(), context, request).await
            })
        }
        fn revoke(&self, context: __LensoNativeSupportHumanApiToken::InvocationContext, request: $crate::RevokeRequest) -> __LensoNativeSupportHumanApiToken::NativeRequestFuture<$crate::HumanApiTokenRevoke> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::HumanApiTokenProvider>::revoke(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct HumanApiTokenRequestEndpoint { provider: Rc<dyn HumanApiTokenProvider> }

#[derive(Debug)]
pub struct HumanApiTokenEndpoint<P: HumanApiTokenProvider> { provider: Rc<P>, request_endpoint: HumanApiTokenRequestEndpoint }
impl<P: HumanApiTokenProvider> HumanApiTokenEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn HumanApiTokenProvider> = provider.clone();
        Self { provider, request_endpoint: HumanApiTokenRequestEndpoint { provider: request_provider } }
    }
}

impl<P: HumanApiTokenProvider> NativeRequestEndpoint for HumanApiTokenEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        ISSUE_OPERATION,
        LIST_OPERATION,
        RECEIPT_OPERATION,
        REVOKE_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            ISSUE_OPERATION => {
                let Ok(request) = request.downcast::<IssueRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).issue(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            LIST_OPERATION => {
                let Ok(request) = request.downcast::<ListRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RECEIPT_OPERATION => {
                let Ok(request) = request.downcast::<ReceiptRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).receipt(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            REVOKE_OPERATION => {
                let Ok(request) = request.downcast::<RevokeRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).revoke(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_human_api_token {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::HumanApiTokenEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_human_api_token {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_human_api_token!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct HumanApiTokenClient {
    issue: NativeRequestHandle<HumanApiTokenIssue>,
    list: NativeRequestHandle<HumanApiTokenList>,
    receipt: NativeRequestHandle<HumanApiTokenReceipt>,
    revoke: NativeRequestHandle<HumanApiTokenRevoke>,
}
impl HumanApiTokenClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn issue(&self, request: IssueRequest) -> Result<IssueResponse, HumanApiTokenIssueInvocationError> {
        self.issue.invoke(ISSUE_OPERATION, request).await
            .map_err(HumanApiTokenIssueInvocationError::Runtime)?
            .map_err(HumanApiTokenIssueInvocationError::Domain)
    }

    pub async fn issue_with_context(&self, context: InvocationContext, request: IssueRequest) -> Result<IssueResponse, HumanApiTokenIssueInvocationError> {
        self.issue.invoke_with_context(ISSUE_OPERATION, context, request).await
            .map_err(HumanApiTokenIssueInvocationError::Runtime)?
            .map_err(HumanApiTokenIssueInvocationError::Domain)
    }

    pub async fn list(&self, request: ListRequest) -> Result<ListResponse, HumanApiTokenListInvocationError> {
        self.list.invoke(LIST_OPERATION, request).await
            .map_err(HumanApiTokenListInvocationError::Runtime)?
            .map_err(HumanApiTokenListInvocationError::Domain)
    }

    pub async fn list_with_context(&self, context: InvocationContext, request: ListRequest) -> Result<ListResponse, HumanApiTokenListInvocationError> {
        self.list.invoke_with_context(LIST_OPERATION, context, request).await
            .map_err(HumanApiTokenListInvocationError::Runtime)?
            .map_err(HumanApiTokenListInvocationError::Domain)
    }

    pub async fn receipt(&self, request: ReceiptRequest) -> Result<ReceiptResponse, HumanApiTokenReceiptInvocationError> {
        self.receipt.invoke(RECEIPT_OPERATION, request).await
            .map_err(HumanApiTokenReceiptInvocationError::Runtime)?
            .map_err(HumanApiTokenReceiptInvocationError::Domain)
    }

    pub async fn receipt_with_context(&self, context: InvocationContext, request: ReceiptRequest) -> Result<ReceiptResponse, HumanApiTokenReceiptInvocationError> {
        self.receipt.invoke_with_context(RECEIPT_OPERATION, context, request).await
            .map_err(HumanApiTokenReceiptInvocationError::Runtime)?
            .map_err(HumanApiTokenReceiptInvocationError::Domain)
    }

    pub async fn revoke(&self, request: RevokeRequest) -> Result<RevokeResponse, HumanApiTokenRevokeInvocationError> {
        self.revoke.invoke(REVOKE_OPERATION, request).await
            .map_err(HumanApiTokenRevokeInvocationError::Runtime)?
            .map_err(HumanApiTokenRevokeInvocationError::Domain)
    }

    pub async fn revoke_with_context(&self, context: InvocationContext, request: RevokeRequest) -> Result<RevokeResponse, HumanApiTokenRevokeInvocationError> {
        self.revoke.invoke_with_context(REVOKE_OPERATION, context, request).await
            .map_err(HumanApiTokenRevokeInvocationError::Runtime)?
            .map_err(HumanApiTokenRevokeInvocationError::Domain)
    }
}

impl CapabilityClient for HumanApiTokenClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            issue: dependencies.one::<HumanApiTokenIssue>()?,
            list: dependencies.one::<HumanApiTokenList>()?,
            receipt: dependencies.one::<HumanApiTokenReceipt>()?,
            revoke: dependencies.one::<HumanApiTokenRevoke>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for HumanApiTokenClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    issue: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<HumanApiTokenIssue>()?,
                    list: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<HumanApiTokenList>()?,
                    receipt: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<HumanApiTokenReceipt>()?,
                    revoke: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<HumanApiTokenRevoke>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum HumanApiTokenIssueInvocationError {
    Domain(IssueError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum HumanApiTokenListInvocationError {
    Domain(ListError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum HumanApiTokenReceiptInvocationError {
    Domain(ReceiptError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum HumanApiTokenRevokeInvocationError {
    Domain(RevokeError),
    Runtime(RuntimeFailure),
}
