// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.auth.oidc-provider@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:991c54e7ee344821be483e18072d31c7ce42c967e6c0e2965d15b424c63fbea7";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const OIDC_PROVIDER_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const OIDC_PROVIDER_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const OIDC_PROVIDER_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const OIDC_PROVIDER_CONTRACT: CapabilityReference<OidcProviderClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_oidc_provider { () => { "{\"capability_id\":\"lenso.auth.oidc-provider@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"authorize\",\"exchange\",\"jwks\",\"metadata\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_oidc_provider_client {
    () => { "{\"capability_id\":\"lenso.auth.oidc-provider@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.oidc-provider@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_oidc_provider_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.oidc-provider@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_oidc_provider_client {
    () => { "{\"capability_id\":\"lenso.auth.oidc-provider@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.oidc-provider@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const AUTHORIZE_OPERATION: &str = "authorize";
pub const EXCHANGE_OPERATION: &str = "exchange";
pub const JWKS_OPERATION: &str = "jwks";
pub const METADATA_OPERATION: &str = "metadata";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AuthorizeRequest {
    #[serde(rename = "client_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub client_id: String,
    #[serde(rename = "code_challenge")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub code_challenge: String,
    #[serde(rename = "code_challenge_method")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub code_challenge_method: String,
    #[serde(rename = "nonce")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub nonce: Option<String>,
    #[serde(rename = "redirect_uri")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub redirect_uri: String,
    #[serde(rename = "response_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub response_type: String,
    #[serde(rename = "scope")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope: String,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: Option<String>,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AuthorizeResponse {
    #[serde(rename = "code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub code: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "redirect_uri")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub redirect_uri: String,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: Option<String>,
}

impl fmt::Debug for AuthorizeResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("AuthorizeResponse")
            .field("code", &"<redacted>")
            .field("expires_at", &self.expires_at)
            .field("redirect_uri", &self.redirect_uri)
            .field("state", &self.state)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum AuthorizeError {
    DisabledSubject,
    Forbidden,
    InvalidClient,
    InvalidPkce,
    InvalidRedirectUri,
    InvalidRequest,
    InvalidScope,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExchangeRequest {
    #[serde(rename = "client_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub client_id: String,
    #[serde(rename = "code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub code: String,
    #[serde(rename = "code_verifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub code_verifier: String,
    #[serde(rename = "grant_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub grant_type: String,
    #[serde(rename = "redirect_uri")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub redirect_uri: String,
}

impl fmt::Debug for ExchangeRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ExchangeRequest")
            .field("client_id", &self.client_id)
            .field("code", &"<redacted>")
            .field("code_verifier", &"<redacted>")
            .field("grant_type", &self.grant_type)
            .field("redirect_uri", &self.redirect_uri)
            .finish()
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExchangeResponse {
    #[serde(rename = "access_token")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub access_token: String,
    #[serde(rename = "expires_in")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_in: i64,
    #[serde(rename = "id_token")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id_token: String,
    #[serde(rename = "scope")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope: String,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
    #[serde(rename = "token_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub token_type: String,
}

impl fmt::Debug for ExchangeResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ExchangeResponse")
            .field("access_token", &"<redacted>")
            .field("expires_in", &self.expires_in)
            .field("id_token", &"<redacted>")
            .field("scope", &self.scope)
            .field("session_id", &self.session_id)
            .field("token_type", &self.token_type)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ExchangeError {
    DisabledSubject,
    InvalidGrant,
    InvalidRequest,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct EmptyRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct JwksResponse {
    #[serde(rename = "jwks")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub jwks: std::collections::BTreeMap<String, serde_json::Value>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum JwksError {
    Disabled,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct MetadataResponse {
    #[serde(rename = "authorization_endpoint")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub authorization_endpoint: String,
    #[serde(rename = "client_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub client_id: String,
    #[serde(rename = "issuer")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub issuer: String,
    #[serde(rename = "jwks_uri")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub jwks_uri: String,
    #[serde(rename = "scopes_supported")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scopes_supported: Vec<String>,
    #[serde(rename = "token_endpoint")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub token_endpoint: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum MetadataError {
    Disabled,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct OidcProviderAuthorize;
impl RequestCapability for OidcProviderAuthorize {
    type Request = AuthorizeRequest;
    type Response = AuthorizeResponse;
    type DomainError = AuthorizeError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != AUTHORIZE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OidcProviderRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).authorize(context, request)
    }
}

#[derive(Debug)]
pub struct OidcProviderExchange;
impl RequestCapability for OidcProviderExchange {
    type Request = ExchangeRequest;
    type Response = ExchangeResponse;
    type DomainError = ExchangeError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != EXCHANGE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OidcProviderRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).exchange(context, request)
    }
}

#[derive(Debug)]
pub struct OidcProviderJwks;
impl RequestCapability for OidcProviderJwks {
    type Request = EmptyRequest;
    type Response = JwksResponse;
    type DomainError = JwksError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != JWKS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OidcProviderRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).jwks(context, request)
    }
}

#[derive(Debug)]
pub struct OidcProviderMetadata;
impl RequestCapability for OidcProviderMetadata {
    type Request = EmptyRequest;
    type Response = MetadataResponse;
    type DomainError = MetadataError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != METADATA_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OidcProviderRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).metadata(context, request)
    }
}

impl serde::Serialize for AuthorizeError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::DisabledSubject => serializer.serialize_str("disabled_subject"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidClient => serializer.serialize_str("invalid_client"),
            Self::InvalidPkce => serializer.serialize_str("invalid_pkce"),
            Self::InvalidRedirectUri => serializer.serialize_str("invalid_redirect_uri"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidScope => serializer.serialize_str("invalid_scope"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for AuthorizeError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "disabled_subject" => Ok(Self::DisabledSubject),
                "forbidden" => Ok(Self::Forbidden),
                "invalid_client" => Ok(Self::InvalidClient),
                "invalid_pkce" => Ok(Self::InvalidPkce),
                "invalid_redirect_uri" => Ok(Self::InvalidRedirectUri),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_scope" => Ok(Self::InvalidScope),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ExchangeError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::DisabledSubject => serializer.serialize_str("disabled_subject"),
            Self::InvalidGrant => serializer.serialize_str("invalid_grant"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ExchangeError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "disabled_subject" => Ok(Self::DisabledSubject),
                "invalid_grant" => Ok(Self::InvalidGrant),
                "invalid_request" => Ok(Self::InvalidRequest),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for JwksError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Disabled => serializer.serialize_str("disabled"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for JwksError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "disabled" => Ok(Self::Disabled),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for MetadataError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Disabled => serializer.serialize_str("disabled"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for MetadataError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "disabled" => Ok(Self::Disabled),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_authorize_request(value: &AuthorizeRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_authorize_request(wire: &str) -> Result<AuthorizeRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_authorize_response(value: &AuthorizeResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_authorize_response(wire: &str) -> Result<AuthorizeResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_authorize_error(value: &AuthorizeError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_authorize_error(wire: &str) -> Result<AuthorizeError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_exchange_request(value: &ExchangeRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_exchange_request(wire: &str) -> Result<ExchangeRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_exchange_response(value: &ExchangeResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_exchange_response(wire: &str) -> Result<ExchangeResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_exchange_error(value: &ExchangeError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_exchange_error(wire: &str) -> Result<ExchangeError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_jwks_request(value: &EmptyRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_jwks_request(wire: &str) -> Result<EmptyRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_jwks_response(value: &JwksResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_jwks_response(wire: &str) -> Result<JwksResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_jwks_error(value: &JwksError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_jwks_error(wire: &str) -> Result<JwksError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_metadata_request(value: &EmptyRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_metadata_request(wire: &str) -> Result<EmptyRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_metadata_response(value: &MetadataResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_metadata_response(wire: &str) -> Result<MetadataResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_metadata_error(value: &MetadataError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_metadata_error(wire: &str) -> Result<MetadataError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoOidcProviderAuthorizeResult {
    fn __lenso_into_result(self) -> Result<Result<AuthorizeResponse, AuthorizeError>, RuntimeFailure>;
}
impl __LensoIntoOidcProviderAuthorizeResult for Result<AuthorizeResponse, AuthorizeError> {
    fn __lenso_into_result(self) -> Result<Result<AuthorizeResponse, AuthorizeError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOidcProviderAuthorizeResult for Result<Result<AuthorizeResponse, AuthorizeError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<AuthorizeResponse, AuthorizeError>, RuntimeFailure> { self }
}
impl __LensoIntoOidcProviderAuthorizeResult for Result<AuthorizeResponse, lenso_plugin_authoring::PluginError<AuthorizeError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<AuthorizeResponse, AuthorizeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOidcProviderAuthorizeResult for Result<AuthorizeResponse, OidcProviderAuthorizeInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<AuthorizeResponse, AuthorizeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OidcProviderAuthorizeInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OidcProviderAuthorizeInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOidcProviderExchangeResult {
    fn __lenso_into_result(self) -> Result<Result<ExchangeResponse, ExchangeError>, RuntimeFailure>;
}
impl __LensoIntoOidcProviderExchangeResult for Result<ExchangeResponse, ExchangeError> {
    fn __lenso_into_result(self) -> Result<Result<ExchangeResponse, ExchangeError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOidcProviderExchangeResult for Result<Result<ExchangeResponse, ExchangeError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ExchangeResponse, ExchangeError>, RuntimeFailure> { self }
}
impl __LensoIntoOidcProviderExchangeResult for Result<ExchangeResponse, lenso_plugin_authoring::PluginError<ExchangeError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ExchangeResponse, ExchangeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOidcProviderExchangeResult for Result<ExchangeResponse, OidcProviderExchangeInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ExchangeResponse, ExchangeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OidcProviderExchangeInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OidcProviderExchangeInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOidcProviderJwksResult {
    fn __lenso_into_result(self) -> Result<Result<JwksResponse, JwksError>, RuntimeFailure>;
}
impl __LensoIntoOidcProviderJwksResult for Result<JwksResponse, JwksError> {
    fn __lenso_into_result(self) -> Result<Result<JwksResponse, JwksError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOidcProviderJwksResult for Result<Result<JwksResponse, JwksError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<JwksResponse, JwksError>, RuntimeFailure> { self }
}
impl __LensoIntoOidcProviderJwksResult for Result<JwksResponse, lenso_plugin_authoring::PluginError<JwksError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<JwksResponse, JwksError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOidcProviderJwksResult for Result<JwksResponse, OidcProviderJwksInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<JwksResponse, JwksError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OidcProviderJwksInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OidcProviderJwksInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOidcProviderMetadataResult {
    fn __lenso_into_result(self) -> Result<Result<MetadataResponse, MetadataError>, RuntimeFailure>;
}
impl __LensoIntoOidcProviderMetadataResult for Result<MetadataResponse, MetadataError> {
    fn __lenso_into_result(self) -> Result<Result<MetadataResponse, MetadataError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOidcProviderMetadataResult for Result<Result<MetadataResponse, MetadataError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<MetadataResponse, MetadataError>, RuntimeFailure> { self }
}
impl __LensoIntoOidcProviderMetadataResult for Result<MetadataResponse, lenso_plugin_authoring::PluginError<MetadataError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<MetadataResponse, MetadataError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOidcProviderMetadataResult for Result<MetadataResponse, OidcProviderMetadataInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<MetadataResponse, MetadataError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OidcProviderMetadataInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OidcProviderMetadataInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait OidcProviderProvider: fmt::Debug + 'static {
    fn authorize(&self, context: InvocationContext, request: AuthorizeRequest) -> NativeRequestFuture<OidcProviderAuthorize>;
    fn exchange(&self, context: InvocationContext, request: ExchangeRequest) -> NativeRequestFuture<OidcProviderExchange>;
    fn jwks(&self, context: InvocationContext, request: EmptyRequest) -> NativeRequestFuture<OidcProviderJwks>;
    fn metadata(&self, context: InvocationContext, request: EmptyRequest) -> NativeRequestFuture<OidcProviderMetadata>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_oidc_provider {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportOidcProvider;
        impl $crate::OidcProviderProvider for $plugin {
        fn authorize(&self, context: __LensoNativeSupportOidcProvider::InvocationContext, request: $crate::AuthorizeRequest) -> __LensoNativeSupportOidcProvider::NativeRequestFuture<$crate::OidcProviderAuthorize> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::authorize(&plugin, context, request).await;
                $crate::__LensoIntoOidcProviderAuthorizeResult::__lenso_into_result(result)
            })
        }
        fn exchange(&self, context: __LensoNativeSupportOidcProvider::InvocationContext, request: $crate::ExchangeRequest) -> __LensoNativeSupportOidcProvider::NativeRequestFuture<$crate::OidcProviderExchange> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::exchange(&plugin, context, request).await;
                $crate::__LensoIntoOidcProviderExchangeResult::__lenso_into_result(result)
            })
        }
        fn jwks(&self, context: __LensoNativeSupportOidcProvider::InvocationContext, request: $crate::EmptyRequest) -> __LensoNativeSupportOidcProvider::NativeRequestFuture<$crate::OidcProviderJwks> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::jwks(&plugin, context, request).await;
                $crate::__LensoIntoOidcProviderJwksResult::__lenso_into_result(result)
            })
        }
        fn metadata(&self, context: __LensoNativeSupportOidcProvider::InvocationContext, request: $crate::EmptyRequest) -> __LensoNativeSupportOidcProvider::NativeRequestFuture<$crate::OidcProviderMetadata> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::metadata(&plugin, context, request).await;
                $crate::__LensoIntoOidcProviderMetadataResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_oidc_provider {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportOidcProvider;
        impl $crate::OidcProviderProvider for $object {
        fn authorize(&self, context: __LensoNativeSupportOidcProvider::InvocationContext, request: $crate::AuthorizeRequest) -> __LensoNativeSupportOidcProvider::NativeRequestFuture<$crate::OidcProviderAuthorize> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::authorize(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoOidcProviderAuthorizeResult::__lenso_into_result(result)
            })
        }
        fn exchange(&self, context: __LensoNativeSupportOidcProvider::InvocationContext, request: $crate::ExchangeRequest) -> __LensoNativeSupportOidcProvider::NativeRequestFuture<$crate::OidcProviderExchange> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::exchange(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoOidcProviderExchangeResult::__lenso_into_result(result)
            })
        }
        fn jwks(&self, context: __LensoNativeSupportOidcProvider::InvocationContext, request: $crate::EmptyRequest) -> __LensoNativeSupportOidcProvider::NativeRequestFuture<$crate::OidcProviderJwks> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::jwks(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoOidcProviderJwksResult::__lenso_into_result(result)
            })
        }
        fn metadata(&self, context: __LensoNativeSupportOidcProvider::InvocationContext, request: $crate::EmptyRequest) -> __LensoNativeSupportOidcProvider::NativeRequestFuture<$crate::OidcProviderMetadata> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::metadata(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoOidcProviderMetadataResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_oidc_provider {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportOidcProvider;
        impl $crate::OidcProviderProvider for $object {
        fn authorize(&self, context: __LensoNativeSupportOidcProvider::InvocationContext, request: $crate::AuthorizeRequest) -> __LensoNativeSupportOidcProvider::NativeRequestFuture<$crate::OidcProviderAuthorize> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::OidcProviderProvider>::authorize(plugin.as_ref(), context, request).await
            })
        }
        fn exchange(&self, context: __LensoNativeSupportOidcProvider::InvocationContext, request: $crate::ExchangeRequest) -> __LensoNativeSupportOidcProvider::NativeRequestFuture<$crate::OidcProviderExchange> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::OidcProviderProvider>::exchange(plugin.as_ref(), context, request).await
            })
        }
        fn jwks(&self, context: __LensoNativeSupportOidcProvider::InvocationContext, request: $crate::EmptyRequest) -> __LensoNativeSupportOidcProvider::NativeRequestFuture<$crate::OidcProviderJwks> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::OidcProviderProvider>::jwks(plugin.as_ref(), context, request).await
            })
        }
        fn metadata(&self, context: __LensoNativeSupportOidcProvider::InvocationContext, request: $crate::EmptyRequest) -> __LensoNativeSupportOidcProvider::NativeRequestFuture<$crate::OidcProviderMetadata> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::OidcProviderProvider>::metadata(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct OidcProviderRequestEndpoint { provider: Rc<dyn OidcProviderProvider> }

#[derive(Debug)]
pub struct OidcProviderEndpoint<P: OidcProviderProvider> { provider: Rc<P>, request_endpoint: OidcProviderRequestEndpoint }
impl<P: OidcProviderProvider> OidcProviderEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn OidcProviderProvider> = provider.clone();
        Self { provider, request_endpoint: OidcProviderRequestEndpoint { provider: request_provider } }
    }
}

impl<P: OidcProviderProvider> NativeRequestEndpoint for OidcProviderEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        AUTHORIZE_OPERATION,
        EXCHANGE_OPERATION,
        JWKS_OPERATION,
        METADATA_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            AUTHORIZE_OPERATION => {
                let Ok(request) = request.downcast::<AuthorizeRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).authorize(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            EXCHANGE_OPERATION => {
                let Ok(request) = request.downcast::<ExchangeRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).exchange(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            JWKS_OPERATION => {
                let Ok(request) = request.downcast::<EmptyRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).jwks(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            METADATA_OPERATION => {
                let Ok(request) = request.downcast::<EmptyRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).metadata(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_oidc_provider {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::OidcProviderEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_oidc_provider {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_oidc_provider!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct OidcProviderClient {
    authorize: NativeRequestHandle<OidcProviderAuthorize>,
    exchange: NativeRequestHandle<OidcProviderExchange>,
    jwks: NativeRequestHandle<OidcProviderJwks>,
    metadata: NativeRequestHandle<OidcProviderMetadata>,
}
impl OidcProviderClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn authorize(&self, request: AuthorizeRequest) -> Result<AuthorizeResponse, OidcProviderAuthorizeInvocationError> {
        self.authorize.invoke(AUTHORIZE_OPERATION, request).await
            .map_err(OidcProviderAuthorizeInvocationError::Runtime)?
            .map_err(OidcProviderAuthorizeInvocationError::Domain)
    }

    pub async fn authorize_with_context(&self, context: InvocationContext, request: AuthorizeRequest) -> Result<AuthorizeResponse, OidcProviderAuthorizeInvocationError> {
        self.authorize.invoke_with_context(AUTHORIZE_OPERATION, context, request).await
            .map_err(OidcProviderAuthorizeInvocationError::Runtime)?
            .map_err(OidcProviderAuthorizeInvocationError::Domain)
    }

    pub async fn exchange(&self, request: ExchangeRequest) -> Result<ExchangeResponse, OidcProviderExchangeInvocationError> {
        self.exchange.invoke(EXCHANGE_OPERATION, request).await
            .map_err(OidcProviderExchangeInvocationError::Runtime)?
            .map_err(OidcProviderExchangeInvocationError::Domain)
    }

    pub async fn exchange_with_context(&self, context: InvocationContext, request: ExchangeRequest) -> Result<ExchangeResponse, OidcProviderExchangeInvocationError> {
        self.exchange.invoke_with_context(EXCHANGE_OPERATION, context, request).await
            .map_err(OidcProviderExchangeInvocationError::Runtime)?
            .map_err(OidcProviderExchangeInvocationError::Domain)
    }

    pub async fn jwks(&self, request: EmptyRequest) -> Result<JwksResponse, OidcProviderJwksInvocationError> {
        self.jwks.invoke(JWKS_OPERATION, request).await
            .map_err(OidcProviderJwksInvocationError::Runtime)?
            .map_err(OidcProviderJwksInvocationError::Domain)
    }

    pub async fn jwks_with_context(&self, context: InvocationContext, request: EmptyRequest) -> Result<JwksResponse, OidcProviderJwksInvocationError> {
        self.jwks.invoke_with_context(JWKS_OPERATION, context, request).await
            .map_err(OidcProviderJwksInvocationError::Runtime)?
            .map_err(OidcProviderJwksInvocationError::Domain)
    }

    pub async fn metadata(&self, request: EmptyRequest) -> Result<MetadataResponse, OidcProviderMetadataInvocationError> {
        self.metadata.invoke(METADATA_OPERATION, request).await
            .map_err(OidcProviderMetadataInvocationError::Runtime)?
            .map_err(OidcProviderMetadataInvocationError::Domain)
    }

    pub async fn metadata_with_context(&self, context: InvocationContext, request: EmptyRequest) -> Result<MetadataResponse, OidcProviderMetadataInvocationError> {
        self.metadata.invoke_with_context(METADATA_OPERATION, context, request).await
            .map_err(OidcProviderMetadataInvocationError::Runtime)?
            .map_err(OidcProviderMetadataInvocationError::Domain)
    }
}

impl CapabilityClient for OidcProviderClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            authorize: dependencies.one::<OidcProviderAuthorize>()?,
            exchange: dependencies.one::<OidcProviderExchange>()?,
            jwks: dependencies.one::<OidcProviderJwks>()?,
            metadata: dependencies.one::<OidcProviderMetadata>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for OidcProviderClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    authorize: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OidcProviderAuthorize>()?,
                    exchange: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OidcProviderExchange>()?,
                    jwks: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OidcProviderJwks>()?,
                    metadata: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OidcProviderMetadata>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum OidcProviderAuthorizeInvocationError {
    Domain(AuthorizeError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OidcProviderExchangeInvocationError {
    Domain(ExchangeError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OidcProviderJwksInvocationError {
    Domain(JwksError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OidcProviderMetadataInvocationError {
    Domain(MetadataError),
    Runtime(RuntimeFailure),
}
