// Generated by workers/generate-migrations.py. Do not edit.
//! Explicit D1 schema operator and read-only runtime verification.
use crate::workers::D1Binding;
use lenso_migration::Migration;
use lenso_migration_d1::{Error, LegacySchema, Plan, SqlMigration, Statement, Transport};

const MIGRATIONS: &[Migration] = &[
    Migration::new(
        1,
        "account",
        include_str!("../migrations/d1/001_account.sql"),
    ),
    Migration::new(
        2,
        "pagination-indexes",
        include_str!("../migrations/d1/002_pagination_indexes.sql"),
    ),
];
const SQL: &[SqlMigration] = &[
    SqlMigration {
        migration: MIGRATIONS[0],
        statement_ends: &[190, 467, 748, 825, 1404, 1473, 1701, 1798, 1909],
    },
    SqlMigration {
        migration: MIGRATIONS[1],
        statement_ends: &[161],
    },
];
pub fn plan() -> Result<Plan, Error> {
    Plan::new(
        "lenso.auth.account",
        SQL,
        MIGRATIONS,
        Some(LegacySchema {
            table: "auth_account_schema",
            fingerprint: "e2ab982504b77776e928387519fb612fcd4b0213007713ad5389d79910a1db12",
        }),
    )
}

impl Transport for D1Binding {
    fn batch(
        &self,
        statements: Vec<Statement>,
    ) -> std::pin::Pin<
        Box<dyn std::future::Future<Output = Result<Vec<Vec<serde_json::Value>>, Error>> + '_>,
    > {
        Box::pin(async move {
            self.run(
                statements
                    .into_iter()
                    .map(|s| crate::workers::statement(s.sql, s.params))
                    .collect(),
            )
            .await
            .map(|results| results.into_iter().map(|r| r.results).collect())
            .map_err(|()| Error::Transport)
        })
    }
}

/// Runtime Ready gate; never changes storage.
pub async fn verify(binding: &D1Binding) -> Result<(), Error> {
    plan()?.verify(binding).await
}
/// Explicit deployment operation for a fresh dedicated database.
pub async fn setup(binding: &D1Binding) -> Result<(), Error> {
    plan()?.setup(binding).await
}
/// Explicit deployment operation for an existing managed database.
pub async fn upgrade(binding: &D1Binding) -> Result<(), Error> {
    plan()?.upgrade(binding).await
}
/// Explicitly register the known legacy v1, without replaying its SQL.
pub async fn adopt_legacy(binding: &D1Binding) -> Result<(), Error> {
    plan()?.adopt_legacy(binding).await
}
