// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.auth.account-admin@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:3b8010924c71f185dceb5662fb55106d87865ea6683cad76cbbdb71a9a4c67f9";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const ACCOUNT_ADMIN_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const ACCOUNT_ADMIN_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const ACCOUNT_ADMIN_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const ACCOUNT_ADMIN_CONTRACT: CapabilityReference<AccountAdminClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_account_admin { () => { "{\"capability_id\":\"lenso.auth.account-admin@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"list_sessions\",\"list_subjects\",\"set_subject_status\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_account_admin_client {
    () => { "{\"capability_id\":\"lenso.auth.account-admin@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.account-admin@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_account_admin_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.account-admin@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_account_admin_client {
    () => { "{\"capability_id\":\"lenso.auth.account-admin@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.account-admin@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const LIST_SESSIONS_OPERATION: &str = "list_sessions";
pub const LIST_SUBJECTS_OPERATION: &str = "list_subjects";
pub const SET_SUBJECT_STATUS_OPERATION: &str = "set_subject_status";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListSessionsRequest {
    #[serde(rename = "cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cursor: Option<String>,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListSessionsResponse {
    #[serde(rename = "next_cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_cursor: Option<String>,
    #[serde(rename = "sessions")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub sessions: Vec<ListSessionsResponseSessionsItem>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListSessionsResponseSessionsItem {
    #[serde(rename = "actor_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub actor_kind: String,
    #[serde(rename = "assurance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub assurance: String,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "revoked")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revoked: bool,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListSessionsError {
    Forbidden,
    InvalidPage,
    InvalidSubject,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListSubjectsRequest {
    #[serde(rename = "cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cursor: Option<String>,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListSubjectsResponse {
    #[serde(rename = "next_cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_cursor: Option<String>,
    #[serde(rename = "subjects")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subjects: Vec<ListSubjectsResponseSubjectsItem>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListSubjectsResponseSubjectsItem {
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "disabled_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub disabled_reason: Option<String>,
    #[serde(rename = "disabled_until")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub disabled_until: Option<Timestamp>,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: ListSubjectsResponseSubjectsItemStatus,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ListSubjectsResponseSubjectsItemStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "disabled")]
    Disabled,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListSubjectsError {
    Forbidden,
    InvalidPage,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SetSubjectStatusRequest {
    #[serde(rename = "disabled_until")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub disabled_until: Option<Timestamp>,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: Option<String>,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: SetSubjectStatusRequestStatus,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum SetSubjectStatusRequestStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "disabled")]
    Disabled,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SetSubjectStatusResponse {
    #[serde(rename = "changed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub changed: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum SetSubjectStatusError {
    Forbidden,
    InvalidStatus,
    InvalidSubject,
    NotFound,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct AccountAdminListSessions;
impl RequestCapability for AccountAdminListSessions {
    type Request = ListSessionsRequest;
    type Response = ListSessionsResponse;
    type DomainError = ListSessionsError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_SESSIONS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<AccountAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list_sessions(context, request)
    }
}

#[derive(Debug)]
pub struct AccountAdminListSubjects;
impl RequestCapability for AccountAdminListSubjects {
    type Request = ListSubjectsRequest;
    type Response = ListSubjectsResponse;
    type DomainError = ListSubjectsError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_SUBJECTS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<AccountAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list_subjects(context, request)
    }
}

#[derive(Debug)]
pub struct AccountAdminSetSubjectStatus;
impl RequestCapability for AccountAdminSetSubjectStatus {
    type Request = SetSubjectStatusRequest;
    type Response = SetSubjectStatusResponse;
    type DomainError = SetSubjectStatusError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != SET_SUBJECT_STATUS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<AccountAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).set_subject_status(context, request)
    }
}

impl serde::Serialize for ListSessionsError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidPage => serializer.serialize_str("invalid_page"),
            Self::InvalidSubject => serializer.serialize_str("invalid_subject"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListSessionsError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_page" => Ok(Self::InvalidPage),
                "invalid_subject" => Ok(Self::InvalidSubject),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ListSubjectsError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidPage => serializer.serialize_str("invalid_page"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListSubjectsError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_page" => Ok(Self::InvalidPage),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for SetSubjectStatusError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidStatus => serializer.serialize_str("invalid_status"),
            Self::InvalidSubject => serializer.serialize_str("invalid_subject"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for SetSubjectStatusError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_status" => Ok(Self::InvalidStatus),
                "invalid_subject" => Ok(Self::InvalidSubject),
                "not_found" => Ok(Self::NotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_list_sessions_request(value: &ListSessionsRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_sessions_request(wire: &str) -> Result<ListSessionsRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_sessions_response(value: &ListSessionsResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_sessions_response(wire: &str) -> Result<ListSessionsResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_sessions_error(value: &ListSessionsError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_sessions_error(wire: &str) -> Result<ListSessionsError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_list_subjects_request(value: &ListSubjectsRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_subjects_request(wire: &str) -> Result<ListSubjectsRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_subjects_response(value: &ListSubjectsResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_subjects_response(wire: &str) -> Result<ListSubjectsResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_subjects_error(value: &ListSubjectsError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_subjects_error(wire: &str) -> Result<ListSubjectsError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_set_subject_status_request(value: &SetSubjectStatusRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_set_subject_status_request(wire: &str) -> Result<SetSubjectStatusRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_set_subject_status_response(value: &SetSubjectStatusResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_set_subject_status_response(wire: &str) -> Result<SetSubjectStatusResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_set_subject_status_error(value: &SetSubjectStatusError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_set_subject_status_error(wire: &str) -> Result<SetSubjectStatusError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoAccountAdminListSessionsResult {
    fn __lenso_into_result(self) -> Result<Result<ListSessionsResponse, ListSessionsError>, RuntimeFailure>;
}
impl __LensoIntoAccountAdminListSessionsResult for Result<ListSessionsResponse, ListSessionsError> {
    fn __lenso_into_result(self) -> Result<Result<ListSessionsResponse, ListSessionsError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoAccountAdminListSessionsResult for Result<Result<ListSessionsResponse, ListSessionsError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListSessionsResponse, ListSessionsError>, RuntimeFailure> { self }
}
impl __LensoIntoAccountAdminListSessionsResult for Result<ListSessionsResponse, lenso_plugin_authoring::PluginError<ListSessionsError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListSessionsResponse, ListSessionsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoAccountAdminListSessionsResult for Result<ListSessionsResponse, AccountAdminListSessionsInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListSessionsResponse, ListSessionsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(AccountAdminListSessionsInvocationError::Domain(error)) => Ok(Err(error)),
            Err(AccountAdminListSessionsInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoAccountAdminListSubjectsResult {
    fn __lenso_into_result(self) -> Result<Result<ListSubjectsResponse, ListSubjectsError>, RuntimeFailure>;
}
impl __LensoIntoAccountAdminListSubjectsResult for Result<ListSubjectsResponse, ListSubjectsError> {
    fn __lenso_into_result(self) -> Result<Result<ListSubjectsResponse, ListSubjectsError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoAccountAdminListSubjectsResult for Result<Result<ListSubjectsResponse, ListSubjectsError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListSubjectsResponse, ListSubjectsError>, RuntimeFailure> { self }
}
impl __LensoIntoAccountAdminListSubjectsResult for Result<ListSubjectsResponse, lenso_plugin_authoring::PluginError<ListSubjectsError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListSubjectsResponse, ListSubjectsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoAccountAdminListSubjectsResult for Result<ListSubjectsResponse, AccountAdminListSubjectsInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListSubjectsResponse, ListSubjectsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(AccountAdminListSubjectsInvocationError::Domain(error)) => Ok(Err(error)),
            Err(AccountAdminListSubjectsInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoAccountAdminSetSubjectStatusResult {
    fn __lenso_into_result(self) -> Result<Result<SetSubjectStatusResponse, SetSubjectStatusError>, RuntimeFailure>;
}
impl __LensoIntoAccountAdminSetSubjectStatusResult for Result<SetSubjectStatusResponse, SetSubjectStatusError> {
    fn __lenso_into_result(self) -> Result<Result<SetSubjectStatusResponse, SetSubjectStatusError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoAccountAdminSetSubjectStatusResult for Result<Result<SetSubjectStatusResponse, SetSubjectStatusError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<SetSubjectStatusResponse, SetSubjectStatusError>, RuntimeFailure> { self }
}
impl __LensoIntoAccountAdminSetSubjectStatusResult for Result<SetSubjectStatusResponse, lenso_plugin_authoring::PluginError<SetSubjectStatusError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<SetSubjectStatusResponse, SetSubjectStatusError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoAccountAdminSetSubjectStatusResult for Result<SetSubjectStatusResponse, AccountAdminSetSubjectStatusInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<SetSubjectStatusResponse, SetSubjectStatusError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(AccountAdminSetSubjectStatusInvocationError::Domain(error)) => Ok(Err(error)),
            Err(AccountAdminSetSubjectStatusInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait AccountAdminProvider: fmt::Debug + 'static {
    fn list_sessions(&self, context: InvocationContext, request: ListSessionsRequest) -> NativeRequestFuture<AccountAdminListSessions>;
    fn list_subjects(&self, context: InvocationContext, request: ListSubjectsRequest) -> NativeRequestFuture<AccountAdminListSubjects>;
    fn set_subject_status(&self, context: InvocationContext, request: SetSubjectStatusRequest) -> NativeRequestFuture<AccountAdminSetSubjectStatus>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_account_admin {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportAccountAdmin;
        impl $crate::AccountAdminProvider for $plugin {
        fn list_sessions(&self, context: __LensoNativeSupportAccountAdmin::InvocationContext, request: $crate::ListSessionsRequest) -> __LensoNativeSupportAccountAdmin::NativeRequestFuture<$crate::AccountAdminListSessions> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list_sessions(&plugin, context, request).await;
                $crate::__LensoIntoAccountAdminListSessionsResult::__lenso_into_result(result)
            })
        }
        fn list_subjects(&self, context: __LensoNativeSupportAccountAdmin::InvocationContext, request: $crate::ListSubjectsRequest) -> __LensoNativeSupportAccountAdmin::NativeRequestFuture<$crate::AccountAdminListSubjects> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list_subjects(&plugin, context, request).await;
                $crate::__LensoIntoAccountAdminListSubjectsResult::__lenso_into_result(result)
            })
        }
        fn set_subject_status(&self, context: __LensoNativeSupportAccountAdmin::InvocationContext, request: $crate::SetSubjectStatusRequest) -> __LensoNativeSupportAccountAdmin::NativeRequestFuture<$crate::AccountAdminSetSubjectStatus> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::set_subject_status(&plugin, context, request).await;
                $crate::__LensoIntoAccountAdminSetSubjectStatusResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_account_admin {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportAccountAdmin;
        impl $crate::AccountAdminProvider for $object {
        fn list_sessions(&self, context: __LensoNativeSupportAccountAdmin::InvocationContext, request: $crate::ListSessionsRequest) -> __LensoNativeSupportAccountAdmin::NativeRequestFuture<$crate::AccountAdminListSessions> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::list_sessions(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoAccountAdminListSessionsResult::__lenso_into_result(result)
            })
        }
        fn list_subjects(&self, context: __LensoNativeSupportAccountAdmin::InvocationContext, request: $crate::ListSubjectsRequest) -> __LensoNativeSupportAccountAdmin::NativeRequestFuture<$crate::AccountAdminListSubjects> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::list_subjects(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoAccountAdminListSubjectsResult::__lenso_into_result(result)
            })
        }
        fn set_subject_status(&self, context: __LensoNativeSupportAccountAdmin::InvocationContext, request: $crate::SetSubjectStatusRequest) -> __LensoNativeSupportAccountAdmin::NativeRequestFuture<$crate::AccountAdminSetSubjectStatus> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::set_subject_status(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoAccountAdminSetSubjectStatusResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_account_admin {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportAccountAdmin;
        impl $crate::AccountAdminProvider for $object {
        fn list_sessions(&self, context: __LensoNativeSupportAccountAdmin::InvocationContext, request: $crate::ListSessionsRequest) -> __LensoNativeSupportAccountAdmin::NativeRequestFuture<$crate::AccountAdminListSessions> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::AccountAdminProvider>::list_sessions(plugin.as_ref(), context, request).await
            })
        }
        fn list_subjects(&self, context: __LensoNativeSupportAccountAdmin::InvocationContext, request: $crate::ListSubjectsRequest) -> __LensoNativeSupportAccountAdmin::NativeRequestFuture<$crate::AccountAdminListSubjects> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::AccountAdminProvider>::list_subjects(plugin.as_ref(), context, request).await
            })
        }
        fn set_subject_status(&self, context: __LensoNativeSupportAccountAdmin::InvocationContext, request: $crate::SetSubjectStatusRequest) -> __LensoNativeSupportAccountAdmin::NativeRequestFuture<$crate::AccountAdminSetSubjectStatus> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::AccountAdminProvider>::set_subject_status(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct AccountAdminRequestEndpoint { provider: Rc<dyn AccountAdminProvider> }

#[derive(Debug)]
pub struct AccountAdminEndpoint<P: AccountAdminProvider> { provider: Rc<P>, request_endpoint: AccountAdminRequestEndpoint }
impl<P: AccountAdminProvider> AccountAdminEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn AccountAdminProvider> = provider.clone();
        Self { provider, request_endpoint: AccountAdminRequestEndpoint { provider: request_provider } }
    }
}

impl<P: AccountAdminProvider> NativeRequestEndpoint for AccountAdminEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        LIST_SESSIONS_OPERATION,
        LIST_SUBJECTS_OPERATION,
        SET_SUBJECT_STATUS_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            LIST_SESSIONS_OPERATION => {
                let Ok(request) = request.downcast::<ListSessionsRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list_sessions(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            LIST_SUBJECTS_OPERATION => {
                let Ok(request) = request.downcast::<ListSubjectsRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list_subjects(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            SET_SUBJECT_STATUS_OPERATION => {
                let Ok(request) = request.downcast::<SetSubjectStatusRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).set_subject_status(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_account_admin {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::AccountAdminEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_account_admin {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_account_admin!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct AccountAdminClient {
    list_sessions: NativeRequestHandle<AccountAdminListSessions>,
    list_subjects: NativeRequestHandle<AccountAdminListSubjects>,
    set_subject_status: NativeRequestHandle<AccountAdminSetSubjectStatus>,
}
impl AccountAdminClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn list_sessions(&self, request: ListSessionsRequest) -> Result<ListSessionsResponse, AccountAdminListSessionsInvocationError> {
        self.list_sessions.invoke(LIST_SESSIONS_OPERATION, request).await
            .map_err(AccountAdminListSessionsInvocationError::Runtime)?
            .map_err(AccountAdminListSessionsInvocationError::Domain)
    }

    pub async fn list_sessions_with_context(&self, context: InvocationContext, request: ListSessionsRequest) -> Result<ListSessionsResponse, AccountAdminListSessionsInvocationError> {
        self.list_sessions.invoke_with_context(LIST_SESSIONS_OPERATION, context, request).await
            .map_err(AccountAdminListSessionsInvocationError::Runtime)?
            .map_err(AccountAdminListSessionsInvocationError::Domain)
    }

    pub async fn list_subjects(&self, request: ListSubjectsRequest) -> Result<ListSubjectsResponse, AccountAdminListSubjectsInvocationError> {
        self.list_subjects.invoke(LIST_SUBJECTS_OPERATION, request).await
            .map_err(AccountAdminListSubjectsInvocationError::Runtime)?
            .map_err(AccountAdminListSubjectsInvocationError::Domain)
    }

    pub async fn list_subjects_with_context(&self, context: InvocationContext, request: ListSubjectsRequest) -> Result<ListSubjectsResponse, AccountAdminListSubjectsInvocationError> {
        self.list_subjects.invoke_with_context(LIST_SUBJECTS_OPERATION, context, request).await
            .map_err(AccountAdminListSubjectsInvocationError::Runtime)?
            .map_err(AccountAdminListSubjectsInvocationError::Domain)
    }

    pub async fn set_subject_status(&self, request: SetSubjectStatusRequest) -> Result<SetSubjectStatusResponse, AccountAdminSetSubjectStatusInvocationError> {
        self.set_subject_status.invoke(SET_SUBJECT_STATUS_OPERATION, request).await
            .map_err(AccountAdminSetSubjectStatusInvocationError::Runtime)?
            .map_err(AccountAdminSetSubjectStatusInvocationError::Domain)
    }

    pub async fn set_subject_status_with_context(&self, context: InvocationContext, request: SetSubjectStatusRequest) -> Result<SetSubjectStatusResponse, AccountAdminSetSubjectStatusInvocationError> {
        self.set_subject_status.invoke_with_context(SET_SUBJECT_STATUS_OPERATION, context, request).await
            .map_err(AccountAdminSetSubjectStatusInvocationError::Runtime)?
            .map_err(AccountAdminSetSubjectStatusInvocationError::Domain)
    }
}

impl CapabilityClient for AccountAdminClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            list_sessions: dependencies.one::<AccountAdminListSessions>()?,
            list_subjects: dependencies.one::<AccountAdminListSubjects>()?,
            set_subject_status: dependencies.one::<AccountAdminSetSubjectStatus>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for AccountAdminClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    list_sessions: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<AccountAdminListSessions>()?,
                    list_subjects: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<AccountAdminListSubjects>()?,
                    set_subject_status: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<AccountAdminSetSubjectStatus>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum AccountAdminListSessionsInvocationError {
    Domain(ListSessionsError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum AccountAdminListSubjectsInvocationError {
    Domain(ListSubjectsError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum AccountAdminSetSubjectStatusInvocationError {
    Domain(SetSubjectStatusError),
    Runtime(RuntimeFailure),
}
