#!/usr/bin/env python3
"""Generate package-contained D1 plans with SQLite-aware statement offsets.

Run --check in CI. SQL bytes and existing backend version histories are immutable.
"""
import argparse
import json
import re
import sqlite3
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OWNERS = ("account", "oauth-flow", "password", "phone", "device", "api-token", "oidc")


def offsets(sql):
    start = 0
    ends = []
    for index, char in enumerate(sql):
        if char == ";" and sqlite3.complete_statement(sql[start:index + 1]):
            ends.append(len(sql[:index + 1].encode()))
            start = index + 1
    if not ends or sql[start:].strip():
        raise ValueError("D1 migration must contain complete terminated SQLite statements")
    ends[-1] = len(sql.encode())
    return ends


def generate(owner):
    crate = ROOT / "crates" / f"lenso-auth-{owner}-plugin"
    migrations = sorted((crate / "migrations/d1").glob("*.sql"))
    declarations, entries = [], []
    for index, path in enumerate(migrations):
        version = int(path.name.split("_", 1)[0])
        if version != index + 1:
            raise ValueError("D1 versions must remain contiguous")
        name = path.stem.split("_", 1)[1].replace("_", "-")
        declarations.append(f'Migration::new({version}, {json.dumps(name)}, include_str!("../migrations/d1/{path.name}")),')
        entries.append(f'SqlMigration {{ migration: MIGRATIONS[{index}], statement_ends: &{offsets(path.read_bytes().decode())} }},')
    baseline = migrations[0].read_bytes().decode()
    marker = re.search(r"INSERT INTO (\w+) VALUES\(1,'([0-9a-f]{64})'\)", baseline)
    if not marker:
        raise ValueError("explicit legacy marker required for existing Auth v1")
    text = '''// Generated by workers/generate-migrations.py. Do not edit.
//! Explicit D1 schema operator and read-only runtime verification.
use lenso_migration::Migration;
use lenso_migration_d1::{Error, LegacySchema, Plan, SqlMigration, Statement, Transport};
use crate::workers::D1Binding;

const MIGRATIONS: &[Migration] = &[
''' + "\n".join(declarations) + '''
];
const SQL: &[SqlMigration] = &[
''' + "\n".join(entries) + f'''
];
pub fn plan() -> Result<Plan, Error> {{
    Plan::new("lenso.auth.{owner}", SQL, MIGRATIONS, Some(LegacySchema {{ table: "{marker[1]}", fingerprint: "{marker[2]}" }}))
}}
''' + '''
impl Transport for D1Binding {
    fn batch(&self, statements: Vec<Statement>) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<Vec<Vec<serde_json::Value>>, Error>> + '_>> {
        Box::pin(async move {
            self.run(statements.into_iter().map(|s| crate::workers::statement(s.sql, s.params)).collect())
                .await.map(|results| results.into_iter().map(|r| r.results).collect())
                .map_err(|()| Error::Transport)
        })
    }
}

/// Runtime Ready gate; never changes storage.
pub async fn verify(binding: &D1Binding) -> Result<(), Error> { plan()?.verify(binding).await }
/// Explicit deployment operation for a fresh dedicated database.
pub async fn setup(binding: &D1Binding) -> Result<(), Error> { plan()?.setup(binding).await }
/// Explicit deployment operation for an existing managed database.
pub async fn upgrade(binding: &D1Binding) -> Result<(), Error> { plan()?.upgrade(binding).await }
/// Explicitly register the known legacy v1, without replaying its SQL.
pub async fn adopt_legacy(binding: &D1Binding) -> Result<(), Error> { plan()?.adopt_legacy(binding).await }
'''
    # Match repository formatting without editing unrelated files.
    result = subprocess.run(["rustfmt", "+1.94.0", "--edition", "2024"], input=text, text=True, capture_output=True, check=True)
    return crate / "src/migration.rs", result.stdout


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--statements", type=Path, help="Print exact SQLite statements for a proof fixture")
    options = parser.parse_args()
    if options.statements:
        sql = options.statements.read_bytes()
        start = 0
        statements = []
        for end in offsets(sql.decode()):
            statements.append(sql[start:end].decode())
            start = end
        print(json.dumps(statements))
        return
    stale = []
    for owner in OWNERS:
        path, content = generate(owner)
        if options.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content)
    if stale:
        raise SystemExit("Regenerate D1 plans: " + ", ".join(stale))


if __name__ == "__main__":
    main()
