#!/usr/bin/env node
// Canonical implementation: workers/d1.rs. No build-time repository includes.
import {readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';

export const owners = Object.freeze(['account', 'oauth-flow', 'device', 'password', 'oidc', 'phone', 'api-token']);
export function generatedBridge() {
  return '// @generated by node workers/generate-bridges.mjs; DO NOT EDIT.\n'
    + '// Source: workers/d1.rs (private Auth transport).\n'
    + readFileSync(new URL('./d1.rs', import.meta.url), 'utf8');
}
export function generateBridges({check = false} = {}) {
  const expected = generatedBridge();
  const drift = [];
  for (const owner of owners) {
    const path = new URL(`../crates/lenso-auth-${owner}-plugin/src/workers.rs`, import.meta.url);
    let actual;
    try { actual = readFileSync(path, 'utf8'); } catch (error) { if (error.code !== 'ENOENT') throw error; }
    if (actual === expected) continue;
    if (check) drift.push(owner);
    else writeFileSync(path, expected);
  }
  if (drift.length) throw new Error(`Generated D1 bridge drift: ${drift.join(', ')}. Run node workers/generate-bridges.mjs`);
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (process.argv.slice(2).some(arg => arg !== '--check')) throw new Error('Usage: node workers/generate-bridges.mjs [--check]');
  generateBridges({check: process.argv.includes('--check')});
}
