// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.auth.anonymous@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:317e7f6039a2cc6311ee01e19e128c7e06399770599d705ed07a7d85c6011d7f";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const ANONYMOUS_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const ANONYMOUS_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const ANONYMOUS_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const ANONYMOUS_CONTRACT: CapabilityReference<AnonymousClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_anonymous { () => { "{\"capability_id\":\"lenso.auth.anonymous@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"sign_in\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_anonymous_client {
    () => { "{\"capability_id\":\"lenso.auth.anonymous@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.anonymous@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_anonymous_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.anonymous@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_anonymous_client {
    () => { "{\"capability_id\":\"lenso.auth.anonymous@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.auth.anonymous@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const SIGN_IN_OPERATION: &str = "sign_in";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SignInRequest {
    #[serde(rename = "device_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub device_id: Option<String>,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SignInResponse {
    #[serde(rename = "created")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created: bool,
    #[serde(rename = "credential")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

impl fmt::Debug for SignInResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("SignInResponse")
            .field("created", &self.created)
            .field("credential", &"<redacted>")
            .field("expires_at", &self.expires_at)
            .field("session_id", &self.session_id)
            .field("subject", &self.subject)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum SignInError {
    Disabled,
    InvalidDevice,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct Anonymous;
impl RequestCapability for Anonymous {
    type Request = SignInRequest;
    type Response = SignInResponse;
    type DomainError = SignInError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != SIGN_IN_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<AnonymousRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).sign_in(context, request)
    }
}

impl serde::Serialize for SignInError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Disabled => serializer.serialize_str("disabled"),
            Self::InvalidDevice => serializer.serialize_str("invalid_device"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for SignInError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "disabled" => Ok(Self::Disabled),
                "invalid_device" => Ok(Self::InvalidDevice),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_sign_in_request(value: &SignInRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_sign_in_request(wire: &str) -> Result<SignInRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_sign_in_response(value: &SignInResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_sign_in_response(wire: &str) -> Result<SignInResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_sign_in_error(value: &SignInError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_sign_in_error(wire: &str) -> Result<SignInError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoAnonymousSignInResult {
    fn __lenso_into_result(self) -> Result<Result<SignInResponse, SignInError>, RuntimeFailure>;
}
impl __LensoIntoAnonymousSignInResult for Result<SignInResponse, SignInError> {
    fn __lenso_into_result(self) -> Result<Result<SignInResponse, SignInError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoAnonymousSignInResult for Result<Result<SignInResponse, SignInError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<SignInResponse, SignInError>, RuntimeFailure> { self }
}
impl __LensoIntoAnonymousSignInResult for Result<SignInResponse, lenso_plugin_authoring::PluginError<SignInError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<SignInResponse, SignInError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoAnonymousSignInResult for Result<SignInResponse, AnonymousInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<SignInResponse, SignInError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(AnonymousInvocationError::Domain(error)) => Ok(Err(error)),
            Err(AnonymousInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait AnonymousProvider: fmt::Debug + 'static {
    fn sign_in(&self, context: InvocationContext, request: SignInRequest) -> NativeRequestFuture<Anonymous>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_anonymous {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportAnonymous;
        impl $crate::AnonymousProvider for $plugin {
        fn sign_in(&self, context: __LensoNativeSupportAnonymous::InvocationContext, request: $crate::SignInRequest) -> __LensoNativeSupportAnonymous::NativeRequestFuture<$crate::Anonymous> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::sign_in(&plugin, context, request).await;
                $crate::__LensoIntoAnonymousSignInResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_anonymous {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportAnonymous;
        impl $crate::AnonymousProvider for $object {
        fn sign_in(&self, context: __LensoNativeSupportAnonymous::InvocationContext, request: $crate::SignInRequest) -> __LensoNativeSupportAnonymous::NativeRequestFuture<$crate::Anonymous> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::sign_in(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoAnonymousSignInResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_anonymous {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportAnonymous;
        impl $crate::AnonymousProvider for $object {
        fn sign_in(&self, context: __LensoNativeSupportAnonymous::InvocationContext, request: $crate::SignInRequest) -> __LensoNativeSupportAnonymous::NativeRequestFuture<$crate::Anonymous> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::AnonymousProvider>::sign_in(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct AnonymousRequestEndpoint { provider: Rc<dyn AnonymousProvider> }

#[derive(Debug)]
pub struct AnonymousEndpoint<P: AnonymousProvider> { provider: Rc<P>, request_endpoint: AnonymousRequestEndpoint }
impl<P: AnonymousProvider> AnonymousEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn AnonymousProvider> = provider.clone();
        Self { provider, request_endpoint: AnonymousRequestEndpoint { provider: request_provider } }
    }
}

impl<P: AnonymousProvider> NativeRequestEndpoint for AnonymousEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        SIGN_IN_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            SIGN_IN_OPERATION => {
                let Ok(request) = request.downcast::<SignInRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).sign_in(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_anonymous {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::AnonymousEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_anonymous {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_anonymous!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct AnonymousClient {
    sign_in: NativeRequestHandle<Anonymous>,
}
impl AnonymousClient {
    pub fn new(handle: NativeRequestHandle<Anonymous>) -> Self {
        Self { sign_in: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn sign_in(&self, request: SignInRequest) -> Result<SignInResponse, AnonymousInvocationError> {
        self.sign_in.invoke(SIGN_IN_OPERATION, request).await
            .map_err(AnonymousInvocationError::Runtime)?
            .map_err(AnonymousInvocationError::Domain)
    }

    pub async fn sign_in_with_context(&self, context: InvocationContext, request: SignInRequest) -> Result<SignInResponse, AnonymousInvocationError> {
        self.sign_in.invoke_with_context(SIGN_IN_OPERATION, context, request).await
            .map_err(AnonymousInvocationError::Runtime)?
            .map_err(AnonymousInvocationError::Domain)
    }
}

impl CapabilityClient for AnonymousClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            sign_in: dependencies.one::<Anonymous>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for AnonymousClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    sign_in: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<Anonymous>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum AnonymousInvocationError {
    Domain(SignInError),
    Runtime(RuntimeFailure),
}
